// Code generated by ent, DO NOT EDIT.

package webhookreceipt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldProvider, v))
}

// DeliveryID applies equality check predicate on the "delivery_id" field. It's identical to DeliveryIDEQ.
func DeliveryID(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldDeliveryID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldEventType, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldReceivedAt, v))
}

// Accepted applies equality check predicate on the "accepted" field. It's identical to AcceptedEQ.
func Accepted(v bool) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldAccepted, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldContainsFold(FieldProvider, v))
}

// DeliveryIDEQ applies the EQ predicate on the "delivery_id" field.
func DeliveryIDEQ(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldDeliveryID, v))
}

// DeliveryIDNEQ applies the NEQ predicate on the "delivery_id" field.
func DeliveryIDNEQ(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNEQ(FieldDeliveryID, v))
}

// DeliveryIDIn applies the In predicate on the "delivery_id" field.
func DeliveryIDIn(vs ...string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldIn(FieldDeliveryID, vs...))
}

// DeliveryIDNotIn applies the NotIn predicate on the "delivery_id" field.
func DeliveryIDNotIn(vs ...string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNotIn(FieldDeliveryID, vs...))
}

// DeliveryIDGT applies the GT predicate on the "delivery_id" field.
func DeliveryIDGT(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGT(FieldDeliveryID, v))
}

// DeliveryIDGTE applies the GTE predicate on the "delivery_id" field.
func DeliveryIDGTE(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGTE(FieldDeliveryID, v))
}

// DeliveryIDLT applies the LT predicate on the "delivery_id" field.
func DeliveryIDLT(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLT(FieldDeliveryID, v))
}

// DeliveryIDLTE applies the LTE predicate on the "delivery_id" field.
func DeliveryIDLTE(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLTE(FieldDeliveryID, v))
}

// DeliveryIDContains applies the Contains predicate on the "delivery_id" field.
func DeliveryIDContains(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldContains(FieldDeliveryID, v))
}

// DeliveryIDHasPrefix applies the HasPrefix predicate on the "delivery_id" field.
func DeliveryIDHasPrefix(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldHasPrefix(FieldDeliveryID, v))
}

// DeliveryIDHasSuffix applies the HasSuffix predicate on the "delivery_id" field.
func DeliveryIDHasSuffix(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldHasSuffix(FieldDeliveryID, v))
}

// DeliveryIDEqualFold applies the EqualFold predicate on the "delivery_id" field.
func DeliveryIDEqualFold(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEqualFold(FieldDeliveryID, v))
}

// DeliveryIDContainsFold applies the ContainsFold predicate on the "delivery_id" field.
func DeliveryIDContainsFold(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldContainsFold(FieldDeliveryID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldContainsFold(FieldEventType, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldLTE(FieldReceivedAt, v))
}

// AcceptedEQ applies the EQ predicate on the "accepted" field.
func AcceptedEQ(v bool) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldEQ(FieldAccepted, v))
}

// AcceptedNEQ applies the NEQ predicate on the "accepted" field.
func AcceptedNEQ(v bool) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.FieldNEQ(FieldAccepted, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WebhookReceipt) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WebhookReceipt) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WebhookReceipt) predicate.WebhookReceipt {
	return predicate.WebhookReceipt(sql.NotPredicates(p))
}
