// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/ccmate/internal/ent/agentprofile"
)

// AgentProfile is the model entity for the AgentProfile schema.
type AgentProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// SupportsImage holds the value of the "supports_image" field.
	SupportsImage bool `json:"supports_image,omitempty"`
	// SupportsResume holds the value of the "supports_resume" field.
	SupportsResume bool `json:"supports_resume,omitempty"`
	// ConfigJSON holds the value of the "config_json" field.
	ConfigJSON string `json:"config_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentprofile.FieldSupportsImage, agentprofile.FieldSupportsResume:
			values[i] = new(sql.NullBool)
		case agentprofile.FieldID:
			values[i] = new(sql.NullInt64)
		case agentprofile.FieldProvider, agentprofile.FieldModel, agentprofile.FieldConfigJSON:
			values[i] = new(sql.NullString)
		case agentprofile.FieldCreatedAt, agentprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentProfile fields.
func (_m *AgentProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case agentprofile.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case agentprofile.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case agentprofile.FieldSupportsImage:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supports_image", values[i])
			} else if value.Valid {
				_m.SupportsImage = value.Bool
			}
		case agentprofile.FieldSupportsResume:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field supports_resume", values[i])
			} else if value.Valid {
				_m.SupportsResume = value.Bool
			}
		case agentprofile.FieldConfigJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_json", values[i])
			} else if value.Valid {
				_m.ConfigJSON = value.String
			}
		case agentprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agentprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentProfile.
// This includes values selected through modifiers, order, etc.
func (_m *AgentProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AgentProfile.
// Note that you need to call AgentProfile.Unwrap() before calling this method if this AgentProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentProfile) Update() *AgentProfileUpdateOne {
	return NewAgentProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentProfile) Unwrap() *AgentProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentProfile) String() string {
	var builder strings.Builder
	builder.WriteString("AgentProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("supports_image=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupportsImage))
	builder.WriteString(", ")
	builder.WriteString("supports_resume=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupportsResume))
	builder.WriteString(", ")
	builder.WriteString("config_json=")
	builder.WriteString(_m.ConfigJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AgentProfiles is a parsable slice of AgentProfile.
type AgentProfiles []*AgentProfile
