// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/agentprofile"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
)

// AgentProfileUpdate is the builder for updating AgentProfile entities.
type AgentProfileUpdate struct {
	config
	hooks    []Hook
	mutation *AgentProfileMutation
}

// Where appends a list predicates to the AgentProfileUpdate builder.
func (_u *AgentProfileUpdate) Where(ps ...predicate.AgentProfile) *AgentProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AgentProfileUpdate) SetProvider(v string) *AgentProfileUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AgentProfileUpdate) SetNillableProvider(v *string) *AgentProfileUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AgentProfileUpdate) SetModel(v string) *AgentProfileUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AgentProfileUpdate) SetNillableModel(v *string) *AgentProfileUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSupportsImage sets the "supports_image" field.
func (_u *AgentProfileUpdate) SetSupportsImage(v bool) *AgentProfileUpdate {
	_u.mutation.SetSupportsImage(v)
	return _u
}

// SetNillableSupportsImage sets the "supports_image" field if the given value is not nil.
func (_u *AgentProfileUpdate) SetNillableSupportsImage(v *bool) *AgentProfileUpdate {
	if v != nil {
		_u.SetSupportsImage(*v)
	}
	return _u
}

// SetSupportsResume sets the "supports_resume" field.
func (_u *AgentProfileUpdate) SetSupportsResume(v bool) *AgentProfileUpdate {
	_u.mutation.SetSupportsResume(v)
	return _u
}

// SetNillableSupportsResume sets the "supports_resume" field if the given value is not nil.
func (_u *AgentProfileUpdate) SetNillableSupportsResume(v *bool) *AgentProfileUpdate {
	if v != nil {
		_u.SetSupportsResume(*v)
	}
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *AgentProfileUpdate) SetConfigJSON(v string) *AgentProfileUpdate {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// SetNillableConfigJSON sets the "config_json" field if the given value is not nil.
func (_u *AgentProfileUpdate) SetNillableConfigJSON(v *string) *AgentProfileUpdate {
	if v != nil {
		_u.SetConfigJSON(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentProfileUpdate) SetUpdatedAt(v time.Time) *AgentProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AgentProfileMutation object of the builder.
func (_u *AgentProfileUpdate) Mutation() *AgentProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentProfileUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := agentprofile.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AgentProfile.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := agentprofile.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AgentProfile.model": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentprofile.Table, agentprofile.Columns, sqlgraph.NewFieldSpec(agentprofile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(agentprofile.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(agentprofile.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SupportsImage(); ok {
		_spec.SetField(agentprofile.FieldSupportsImage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportsResume(); ok {
		_spec.SetField(agentprofile.FieldSupportsResume, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(agentprofile.FieldConfigJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentProfileUpdateOne is the builder for updating a single AgentProfile entity.
type AgentProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentProfileMutation
}

// SetProvider sets the "provider" field.
func (_u *AgentProfileUpdateOne) SetProvider(v string) *AgentProfileUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AgentProfileUpdateOne) SetNillableProvider(v *string) *AgentProfileUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *AgentProfileUpdateOne) SetModel(v string) *AgentProfileUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *AgentProfileUpdateOne) SetNillableModel(v *string) *AgentProfileUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSupportsImage sets the "supports_image" field.
func (_u *AgentProfileUpdateOne) SetSupportsImage(v bool) *AgentProfileUpdateOne {
	_u.mutation.SetSupportsImage(v)
	return _u
}

// SetNillableSupportsImage sets the "supports_image" field if the given value is not nil.
func (_u *AgentProfileUpdateOne) SetNillableSupportsImage(v *bool) *AgentProfileUpdateOne {
	if v != nil {
		_u.SetSupportsImage(*v)
	}
	return _u
}

// SetSupportsResume sets the "supports_resume" field.
func (_u *AgentProfileUpdateOne) SetSupportsResume(v bool) *AgentProfileUpdateOne {
	_u.mutation.SetSupportsResume(v)
	return _u
}

// SetNillableSupportsResume sets the "supports_resume" field if the given value is not nil.
func (_u *AgentProfileUpdateOne) SetNillableSupportsResume(v *bool) *AgentProfileUpdateOne {
	if v != nil {
		_u.SetSupportsResume(*v)
	}
	return _u
}

// SetConfigJSON sets the "config_json" field.
func (_u *AgentProfileUpdateOne) SetConfigJSON(v string) *AgentProfileUpdateOne {
	_u.mutation.SetConfigJSON(v)
	return _u
}

// SetNillableConfigJSON sets the "config_json" field if the given value is not nil.
func (_u *AgentProfileUpdateOne) SetNillableConfigJSON(v *string) *AgentProfileUpdateOne {
	if v != nil {
		_u.SetConfigJSON(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentProfileUpdateOne) SetUpdatedAt(v time.Time) *AgentProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AgentProfileMutation object of the builder.
func (_u *AgentProfileUpdateOne) Mutation() *AgentProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentProfileUpdate builder.
func (_u *AgentProfileUpdateOne) Where(ps ...predicate.AgentProfile) *AgentProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentProfileUpdateOne) Select(field string, fields ...string) *AgentProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentProfile entity.
func (_u *AgentProfileUpdateOne) Save(ctx context.Context) (*AgentProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentProfileUpdateOne) SaveX(ctx context.Context) *AgentProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := agentprofile.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "AgentProfile.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := agentprofile.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AgentProfile.model": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentProfileUpdateOne) sqlSave(ctx context.Context) (_node *AgentProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentprofile.Table, agentprofile.Columns, sqlgraph.NewFieldSpec(agentprofile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentprofile.FieldID)
		for _, f := range fields {
			if !agentprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(agentprofile.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(agentprofile.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SupportsImage(); ok {
		_spec.SetField(agentprofile.FieldSupportsImage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportsResume(); ok {
		_spec.SetField(agentprofile.FieldSupportsResume, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfigJSON(); ok {
		_spec.SetField(agentprofile.FieldConfigJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AgentProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
