// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/attachment"
	"github.com/cloverstd/ccmate/internal/ent/sessionmessage"
	"github.com/cloverstd/ccmate/internal/ent/task"
)

// AttachmentCreate is the builder for creating a Attachment entity.
type AttachmentCreate struct {
	config
	mutation *AttachmentMutation
	hooks    []Hook
}

// SetFileName sets the "file_name" field.
func (_c *AttachmentCreate) SetFileName(v string) *AttachmentCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *AttachmentCreate) SetMimeType(v string) *AttachmentCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *AttachmentCreate) SetNillableMimeType(v *string) *AttachmentCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *AttachmentCreate) SetSize(v int64) *AttachmentCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *AttachmentCreate) SetNillableSize(v *int64) *AttachmentCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetStoragePath sets the "storage_path" field.
func (_c *AttachmentCreate) SetStoragePath(v string) *AttachmentCreate {
	_c.mutation.SetStoragePath(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AttachmentCreate) SetCreatedAt(v time.Time) *AttachmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AttachmentCreate) SetNillableCreatedAt(v *time.Time) *AttachmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_c *AttachmentCreate) SetTaskID(id int) *AttachmentCreate {
	_c.mutation.SetTaskID(id)
	return _c
}

// SetNillableTaskID sets the "task" edge to the Task entity by ID if the given value is not nil.
func (_c *AttachmentCreate) SetNillableTaskID(id *int) *AttachmentCreate {
	if id != nil {
		_c = _c.SetTaskID(*id)
	}
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *AttachmentCreate) SetTask(v *Task) *AttachmentCreate {
	return _c.SetTaskID(v.ID)
}

// SetMessageID sets the "message" edge to the SessionMessage entity by ID.
func (_c *AttachmentCreate) SetMessageID(id int) *AttachmentCreate {
	_c.mutation.SetMessageID(id)
	return _c
}

// SetNillableMessageID sets the "message" edge to the SessionMessage entity by ID if the given value is not nil.
func (_c *AttachmentCreate) SetNillableMessageID(id *int) *AttachmentCreate {
	if id != nil {
		_c = _c.SetMessageID(*id)
	}
	return _c
}

// SetMessage sets the "message" edge to the SessionMessage entity.
func (_c *AttachmentCreate) SetMessage(v *SessionMessage) *AttachmentCreate {
	return _c.SetMessageID(v.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (_c *AttachmentCreate) Mutation() *AttachmentMutation {
	return _c.mutation
}

// Save creates the Attachment in the database.
func (_c *AttachmentCreate) Save(ctx context.Context) (*Attachment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AttachmentCreate) SaveX(ctx context.Context) *Attachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttachmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttachmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AttachmentCreate) defaults() {
	if _, ok := _c.mutation.MimeType(); !ok {
		v := attachment.DefaultMimeType
		_c.mutation.SetMimeType(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := attachment.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := attachment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AttachmentCreate) check() error {
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "Attachment.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := attachment.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Attachment.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "Attachment.mime_type"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Attachment.size"`)}
	}
	if _, ok := _c.mutation.StoragePath(); !ok {
		return &ValidationError{Name: "storage_path", err: errors.New(`ent: missing required field "Attachment.storage_path"`)}
	}
	if v, ok := _c.mutation.StoragePath(); ok {
		if err := attachment.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`ent: validator failed for field "Attachment.storage_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Attachment.created_at"`)}
	}
	return nil
}

func (_c *AttachmentCreate) sqlSave(ctx context.Context) (*Attachment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AttachmentCreate) createSpec() (*Attachment, *sqlgraph.CreateSpec) {
	var (
		_node = &Attachment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(attachment.Table, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(attachment.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(attachment.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(attachment.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.StoragePath(); ok {
		_spec.SetField(attachment.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(attachment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.TaskTable,
			Columns: []string{attachment.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_attachments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.MessageTable,
			Columns: []string{attachment.MessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.session_message_attachments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AttachmentCreateBulk is the builder for creating many Attachment entities in bulk.
type AttachmentCreateBulk struct {
	config
	err      error
	builders []*AttachmentCreate
}

// Save creates the Attachment entities in the database.
func (_c *AttachmentCreateBulk) Save(ctx context.Context) ([]*Attachment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Attachment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AttachmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AttachmentCreateBulk) SaveX(ctx context.Context) []*Attachment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AttachmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AttachmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
