// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/cloverstd/ccmate/internal/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloverstd/ccmate/internal/ent/agentprofile"
	"github.com/cloverstd/ccmate/internal/ent/attachment"
	"github.com/cloverstd/ccmate/internal/ent/commandaudit"
	"github.com/cloverstd/ccmate/internal/ent/executionlease"
	"github.com/cloverstd/ccmate/internal/ent/project"
	"github.com/cloverstd/ccmate/internal/ent/projectlabelrule"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplate"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplatesnapshot"
	"github.com/cloverstd/ccmate/internal/ent/session"
	"github.com/cloverstd/ccmate/internal/ent/sessionevent"
	"github.com/cloverstd/ccmate/internal/ent/sessionmessage"
	"github.com/cloverstd/ccmate/internal/ent/systemsetting"
	"github.com/cloverstd/ccmate/internal/ent/task"
	"github.com/cloverstd/ccmate/internal/ent/webhookreceipt"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AgentProfile is the client for interacting with the AgentProfile builders.
	AgentProfile *AgentProfileClient
	// Attachment is the client for interacting with the Attachment builders.
	Attachment *AttachmentClient
	// CommandAudit is the client for interacting with the CommandAudit builders.
	CommandAudit *CommandAuditClient
	// ExecutionLease is the client for interacting with the ExecutionLease builders.
	ExecutionLease *ExecutionLeaseClient
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// ProjectLabelRule is the client for interacting with the ProjectLabelRule builders.
	ProjectLabelRule *ProjectLabelRuleClient
	// PromptTemplate is the client for interacting with the PromptTemplate builders.
	PromptTemplate *PromptTemplateClient
	// PromptTemplateSnapshot is the client for interacting with the PromptTemplateSnapshot builders.
	PromptTemplateSnapshot *PromptTemplateSnapshotClient
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
	// SessionEvent is the client for interacting with the SessionEvent builders.
	SessionEvent *SessionEventClient
	// SessionMessage is the client for interacting with the SessionMessage builders.
	SessionMessage *SessionMessageClient
	// SystemSetting is the client for interacting with the SystemSetting builders.
	SystemSetting *SystemSettingClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// WebhookReceipt is the client for interacting with the WebhookReceipt builders.
	WebhookReceipt *WebhookReceiptClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AgentProfile = NewAgentProfileClient(c.config)
	c.Attachment = NewAttachmentClient(c.config)
	c.CommandAudit = NewCommandAuditClient(c.config)
	c.ExecutionLease = NewExecutionLeaseClient(c.config)
	c.Project = NewProjectClient(c.config)
	c.ProjectLabelRule = NewProjectLabelRuleClient(c.config)
	c.PromptTemplate = NewPromptTemplateClient(c.config)
	c.PromptTemplateSnapshot = NewPromptTemplateSnapshotClient(c.config)
	c.Session = NewSessionClient(c.config)
	c.SessionEvent = NewSessionEventClient(c.config)
	c.SessionMessage = NewSessionMessageClient(c.config)
	c.SystemSetting = NewSystemSettingClient(c.config)
	c.Task = NewTaskClient(c.config)
	c.WebhookReceipt = NewWebhookReceiptClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                    ctx,
		config:                 cfg,
		AgentProfile:           NewAgentProfileClient(cfg),
		Attachment:             NewAttachmentClient(cfg),
		CommandAudit:           NewCommandAuditClient(cfg),
		ExecutionLease:         NewExecutionLeaseClient(cfg),
		Project:                NewProjectClient(cfg),
		ProjectLabelRule:       NewProjectLabelRuleClient(cfg),
		PromptTemplate:         NewPromptTemplateClient(cfg),
		PromptTemplateSnapshot: NewPromptTemplateSnapshotClient(cfg),
		Session:                NewSessionClient(cfg),
		SessionEvent:           NewSessionEventClient(cfg),
		SessionMessage:         NewSessionMessageClient(cfg),
		SystemSetting:          NewSystemSettingClient(cfg),
		Task:                   NewTaskClient(cfg),
		WebhookReceipt:         NewWebhookReceiptClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                    ctx,
		config:                 cfg,
		AgentProfile:           NewAgentProfileClient(cfg),
		Attachment:             NewAttachmentClient(cfg),
		CommandAudit:           NewCommandAuditClient(cfg),
		ExecutionLease:         NewExecutionLeaseClient(cfg),
		Project:                NewProjectClient(cfg),
		ProjectLabelRule:       NewProjectLabelRuleClient(cfg),
		PromptTemplate:         NewPromptTemplateClient(cfg),
		PromptTemplateSnapshot: NewPromptTemplateSnapshotClient(cfg),
		Session:                NewSessionClient(cfg),
		SessionEvent:           NewSessionEventClient(cfg),
		SessionMessage:         NewSessionMessageClient(cfg),
		SystemSetting:          NewSystemSettingClient(cfg),
		Task:                   NewTaskClient(cfg),
		WebhookReceipt:         NewWebhookReceiptClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AgentProfile.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AgentProfile, c.Attachment, c.CommandAudit, c.ExecutionLease, c.Project,
		c.ProjectLabelRule, c.PromptTemplate, c.PromptTemplateSnapshot, c.Session,
		c.SessionEvent, c.SessionMessage, c.SystemSetting, c.Task, c.WebhookReceipt,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AgentProfile, c.Attachment, c.CommandAudit, c.ExecutionLease, c.Project,
		c.ProjectLabelRule, c.PromptTemplate, c.PromptTemplateSnapshot, c.Session,
		c.SessionEvent, c.SessionMessage, c.SystemSetting, c.Task, c.WebhookReceipt,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AgentProfileMutation:
		return c.AgentProfile.mutate(ctx, m)
	case *AttachmentMutation:
		return c.Attachment.mutate(ctx, m)
	case *CommandAuditMutation:
		return c.CommandAudit.mutate(ctx, m)
	case *ExecutionLeaseMutation:
		return c.ExecutionLease.mutate(ctx, m)
	case *ProjectMutation:
		return c.Project.mutate(ctx, m)
	case *ProjectLabelRuleMutation:
		return c.ProjectLabelRule.mutate(ctx, m)
	case *PromptTemplateMutation:
		return c.PromptTemplate.mutate(ctx, m)
	case *PromptTemplateSnapshotMutation:
		return c.PromptTemplateSnapshot.mutate(ctx, m)
	case *SessionMutation:
		return c.Session.mutate(ctx, m)
	case *SessionEventMutation:
		return c.SessionEvent.mutate(ctx, m)
	case *SessionMessageMutation:
		return c.SessionMessage.mutate(ctx, m)
	case *SystemSettingMutation:
		return c.SystemSetting.mutate(ctx, m)
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	case *WebhookReceiptMutation:
		return c.WebhookReceipt.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AgentProfileClient is a client for the AgentProfile schema.
type AgentProfileClient struct {
	config
}

// NewAgentProfileClient returns a client for the AgentProfile from the given config.
func NewAgentProfileClient(c config) *AgentProfileClient {
	return &AgentProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `agentprofile.Hooks(f(g(h())))`.
func (c *AgentProfileClient) Use(hooks ...Hook) {
	c.hooks.AgentProfile = append(c.hooks.AgentProfile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `agentprofile.Intercept(f(g(h())))`.
func (c *AgentProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.AgentProfile = append(c.inters.AgentProfile, interceptors...)
}

// Create returns a builder for creating a AgentProfile entity.
func (c *AgentProfileClient) Create() *AgentProfileCreate {
	mutation := newAgentProfileMutation(c.config, OpCreate)
	return &AgentProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AgentProfile entities.
func (c *AgentProfileClient) CreateBulk(builders ...*AgentProfileCreate) *AgentProfileCreateBulk {
	return &AgentProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AgentProfileClient) MapCreateBulk(slice any, setFunc func(*AgentProfileCreate, int)) *AgentProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AgentProfileCreateBulk{err: fmt.Errorf("calling to AgentProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AgentProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AgentProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AgentProfile.
func (c *AgentProfileClient) Update() *AgentProfileUpdate {
	mutation := newAgentProfileMutation(c.config, OpUpdate)
	return &AgentProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AgentProfileClient) UpdateOne(_m *AgentProfile) *AgentProfileUpdateOne {
	mutation := newAgentProfileMutation(c.config, OpUpdateOne, withAgentProfile(_m))
	return &AgentProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AgentProfileClient) UpdateOneID(id int) *AgentProfileUpdateOne {
	mutation := newAgentProfileMutation(c.config, OpUpdateOne, withAgentProfileID(id))
	return &AgentProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AgentProfile.
func (c *AgentProfileClient) Delete() *AgentProfileDelete {
	mutation := newAgentProfileMutation(c.config, OpDelete)
	return &AgentProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AgentProfileClient) DeleteOne(_m *AgentProfile) *AgentProfileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AgentProfileClient) DeleteOneID(id int) *AgentProfileDeleteOne {
	builder := c.Delete().Where(agentprofile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AgentProfileDeleteOne{builder}
}

// Query returns a query builder for AgentProfile.
func (c *AgentProfileClient) Query() *AgentProfileQuery {
	return &AgentProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAgentProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a AgentProfile entity by its id.
func (c *AgentProfileClient) Get(ctx context.Context, id int) (*AgentProfile, error) {
	return c.Query().Where(agentprofile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AgentProfileClient) GetX(ctx context.Context, id int) *AgentProfile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AgentProfileClient) Hooks() []Hook {
	return c.hooks.AgentProfile
}

// Interceptors returns the client interceptors.
func (c *AgentProfileClient) Interceptors() []Interceptor {
	return c.inters.AgentProfile
}

func (c *AgentProfileClient) mutate(ctx context.Context, m *AgentProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AgentProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AgentProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AgentProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AgentProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AgentProfile mutation op: %q", m.Op())
	}
}

// AttachmentClient is a client for the Attachment schema.
type AttachmentClient struct {
	config
}

// NewAttachmentClient returns a client for the Attachment from the given config.
func NewAttachmentClient(c config) *AttachmentClient {
	return &AttachmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `attachment.Hooks(f(g(h())))`.
func (c *AttachmentClient) Use(hooks ...Hook) {
	c.hooks.Attachment = append(c.hooks.Attachment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `attachment.Intercept(f(g(h())))`.
func (c *AttachmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Attachment = append(c.inters.Attachment, interceptors...)
}

// Create returns a builder for creating a Attachment entity.
func (c *AttachmentClient) Create() *AttachmentCreate {
	mutation := newAttachmentMutation(c.config, OpCreate)
	return &AttachmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Attachment entities.
func (c *AttachmentClient) CreateBulk(builders ...*AttachmentCreate) *AttachmentCreateBulk {
	return &AttachmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AttachmentClient) MapCreateBulk(slice any, setFunc func(*AttachmentCreate, int)) *AttachmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AttachmentCreateBulk{err: fmt.Errorf("calling to AttachmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AttachmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AttachmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Attachment.
func (c *AttachmentClient) Update() *AttachmentUpdate {
	mutation := newAttachmentMutation(c.config, OpUpdate)
	return &AttachmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AttachmentClient) UpdateOne(_m *Attachment) *AttachmentUpdateOne {
	mutation := newAttachmentMutation(c.config, OpUpdateOne, withAttachment(_m))
	return &AttachmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AttachmentClient) UpdateOneID(id int) *AttachmentUpdateOne {
	mutation := newAttachmentMutation(c.config, OpUpdateOne, withAttachmentID(id))
	return &AttachmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Attachment.
func (c *AttachmentClient) Delete() *AttachmentDelete {
	mutation := newAttachmentMutation(c.config, OpDelete)
	return &AttachmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AttachmentClient) DeleteOne(_m *Attachment) *AttachmentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AttachmentClient) DeleteOneID(id int) *AttachmentDeleteOne {
	builder := c.Delete().Where(attachment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AttachmentDeleteOne{builder}
}

// Query returns a query builder for Attachment.
func (c *AttachmentClient) Query() *AttachmentQuery {
	return &AttachmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAttachment},
		inters: c.Interceptors(),
	}
}

// Get returns a Attachment entity by its id.
func (c *AttachmentClient) Get(ctx context.Context, id int) (*Attachment, error) {
	return c.Query().Where(attachment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AttachmentClient) GetX(ctx context.Context, id int) *Attachment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a Attachment.
func (c *AttachmentClient) QueryTask(_m *Attachment) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attachment.Table, attachment.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attachment.TaskTable, attachment.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMessage queries the message edge of a Attachment.
func (c *AttachmentClient) QueryMessage(_m *Attachment) *SessionMessageQuery {
	query := (&SessionMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(attachment.Table, attachment.FieldID, id),
			sqlgraph.To(sessionmessage.Table, sessionmessage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, attachment.MessageTable, attachment.MessageColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AttachmentClient) Hooks() []Hook {
	return c.hooks.Attachment
}

// Interceptors returns the client interceptors.
func (c *AttachmentClient) Interceptors() []Interceptor {
	return c.inters.Attachment
}

func (c *AttachmentClient) mutate(ctx context.Context, m *AttachmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AttachmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AttachmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AttachmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AttachmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Attachment mutation op: %q", m.Op())
	}
}

// CommandAuditClient is a client for the CommandAudit schema.
type CommandAuditClient struct {
	config
}

// NewCommandAuditClient returns a client for the CommandAudit from the given config.
func NewCommandAuditClient(c config) *CommandAuditClient {
	return &CommandAuditClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `commandaudit.Hooks(f(g(h())))`.
func (c *CommandAuditClient) Use(hooks ...Hook) {
	c.hooks.CommandAudit = append(c.hooks.CommandAudit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `commandaudit.Intercept(f(g(h())))`.
func (c *CommandAuditClient) Intercept(interceptors ...Interceptor) {
	c.inters.CommandAudit = append(c.inters.CommandAudit, interceptors...)
}

// Create returns a builder for creating a CommandAudit entity.
func (c *CommandAuditClient) Create() *CommandAuditCreate {
	mutation := newCommandAuditMutation(c.config, OpCreate)
	return &CommandAuditCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CommandAudit entities.
func (c *CommandAuditClient) CreateBulk(builders ...*CommandAuditCreate) *CommandAuditCreateBulk {
	return &CommandAuditCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CommandAuditClient) MapCreateBulk(slice any, setFunc func(*CommandAuditCreate, int)) *CommandAuditCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CommandAuditCreateBulk{err: fmt.Errorf("calling to CommandAuditClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CommandAuditCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CommandAuditCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CommandAudit.
func (c *CommandAuditClient) Update() *CommandAuditUpdate {
	mutation := newCommandAuditMutation(c.config, OpUpdate)
	return &CommandAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CommandAuditClient) UpdateOne(_m *CommandAudit) *CommandAuditUpdateOne {
	mutation := newCommandAuditMutation(c.config, OpUpdateOne, withCommandAudit(_m))
	return &CommandAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CommandAuditClient) UpdateOneID(id int) *CommandAuditUpdateOne {
	mutation := newCommandAuditMutation(c.config, OpUpdateOne, withCommandAuditID(id))
	return &CommandAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CommandAudit.
func (c *CommandAuditClient) Delete() *CommandAuditDelete {
	mutation := newCommandAuditMutation(c.config, OpDelete)
	return &CommandAuditDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CommandAuditClient) DeleteOne(_m *CommandAudit) *CommandAuditDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CommandAuditClient) DeleteOneID(id int) *CommandAuditDeleteOne {
	builder := c.Delete().Where(commandaudit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CommandAuditDeleteOne{builder}
}

// Query returns a query builder for CommandAudit.
func (c *CommandAuditClient) Query() *CommandAuditQuery {
	return &CommandAuditQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCommandAudit},
		inters: c.Interceptors(),
	}
}

// Get returns a CommandAudit entity by its id.
func (c *CommandAuditClient) Get(ctx context.Context, id int) (*CommandAudit, error) {
	return c.Query().Where(commandaudit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CommandAuditClient) GetX(ctx context.Context, id int) *CommandAudit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a CommandAudit.
func (c *CommandAuditClient) QueryTask(_m *CommandAudit) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(commandaudit.Table, commandaudit.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commandaudit.TaskTable, commandaudit.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CommandAuditClient) Hooks() []Hook {
	return c.hooks.CommandAudit
}

// Interceptors returns the client interceptors.
func (c *CommandAuditClient) Interceptors() []Interceptor {
	return c.inters.CommandAudit
}

func (c *CommandAuditClient) mutate(ctx context.Context, m *CommandAuditMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CommandAuditCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CommandAuditUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CommandAuditUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CommandAuditDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CommandAudit mutation op: %q", m.Op())
	}
}

// ExecutionLeaseClient is a client for the ExecutionLease schema.
type ExecutionLeaseClient struct {
	config
}

// NewExecutionLeaseClient returns a client for the ExecutionLease from the given config.
func NewExecutionLeaseClient(c config) *ExecutionLeaseClient {
	return &ExecutionLeaseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `executionlease.Hooks(f(g(h())))`.
func (c *ExecutionLeaseClient) Use(hooks ...Hook) {
	c.hooks.ExecutionLease = append(c.hooks.ExecutionLease, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `executionlease.Intercept(f(g(h())))`.
func (c *ExecutionLeaseClient) Intercept(interceptors ...Interceptor) {
	c.inters.ExecutionLease = append(c.inters.ExecutionLease, interceptors...)
}

// Create returns a builder for creating a ExecutionLease entity.
func (c *ExecutionLeaseClient) Create() *ExecutionLeaseCreate {
	mutation := newExecutionLeaseMutation(c.config, OpCreate)
	return &ExecutionLeaseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ExecutionLease entities.
func (c *ExecutionLeaseClient) CreateBulk(builders ...*ExecutionLeaseCreate) *ExecutionLeaseCreateBulk {
	return &ExecutionLeaseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExecutionLeaseClient) MapCreateBulk(slice any, setFunc func(*ExecutionLeaseCreate, int)) *ExecutionLeaseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExecutionLeaseCreateBulk{err: fmt.Errorf("calling to ExecutionLeaseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExecutionLeaseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExecutionLeaseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ExecutionLease.
func (c *ExecutionLeaseClient) Update() *ExecutionLeaseUpdate {
	mutation := newExecutionLeaseMutation(c.config, OpUpdate)
	return &ExecutionLeaseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExecutionLeaseClient) UpdateOne(_m *ExecutionLease) *ExecutionLeaseUpdateOne {
	mutation := newExecutionLeaseMutation(c.config, OpUpdateOne, withExecutionLease(_m))
	return &ExecutionLeaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExecutionLeaseClient) UpdateOneID(id int) *ExecutionLeaseUpdateOne {
	mutation := newExecutionLeaseMutation(c.config, OpUpdateOne, withExecutionLeaseID(id))
	return &ExecutionLeaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ExecutionLease.
func (c *ExecutionLeaseClient) Delete() *ExecutionLeaseDelete {
	mutation := newExecutionLeaseMutation(c.config, OpDelete)
	return &ExecutionLeaseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExecutionLeaseClient) DeleteOne(_m *ExecutionLease) *ExecutionLeaseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExecutionLeaseClient) DeleteOneID(id int) *ExecutionLeaseDeleteOne {
	builder := c.Delete().Where(executionlease.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExecutionLeaseDeleteOne{builder}
}

// Query returns a query builder for ExecutionLease.
func (c *ExecutionLeaseClient) Query() *ExecutionLeaseQuery {
	return &ExecutionLeaseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExecutionLease},
		inters: c.Interceptors(),
	}
}

// Get returns a ExecutionLease entity by its id.
func (c *ExecutionLeaseClient) Get(ctx context.Context, id int) (*ExecutionLease, error) {
	return c.Query().Where(executionlease.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExecutionLeaseClient) GetX(ctx context.Context, id int) *ExecutionLease {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a ExecutionLease.
func (c *ExecutionLeaseClient) QueryTask(_m *ExecutionLease) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(executionlease.Table, executionlease.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, executionlease.TaskTable, executionlease.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ExecutionLeaseClient) Hooks() []Hook {
	return c.hooks.ExecutionLease
}

// Interceptors returns the client interceptors.
func (c *ExecutionLeaseClient) Interceptors() []Interceptor {
	return c.inters.ExecutionLease
}

func (c *ExecutionLeaseClient) mutate(ctx context.Context, m *ExecutionLeaseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExecutionLeaseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExecutionLeaseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExecutionLeaseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExecutionLeaseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ExecutionLease mutation op: %q", m.Op())
	}
}

// ProjectClient is a client for the Project schema.
type ProjectClient struct {
	config
}

// NewProjectClient returns a client for the Project from the given config.
func NewProjectClient(c config) *ProjectClient {
	return &ProjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `project.Hooks(f(g(h())))`.
func (c *ProjectClient) Use(hooks ...Hook) {
	c.hooks.Project = append(c.hooks.Project, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `project.Intercept(f(g(h())))`.
func (c *ProjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.Project = append(c.inters.Project, interceptors...)
}

// Create returns a builder for creating a Project entity.
func (c *ProjectClient) Create() *ProjectCreate {
	mutation := newProjectMutation(c.config, OpCreate)
	return &ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Project entities.
func (c *ProjectClient) CreateBulk(builders ...*ProjectCreate) *ProjectCreateBulk {
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectClient) MapCreateBulk(slice any, setFunc func(*ProjectCreate, int)) *ProjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectCreateBulk{err: fmt.Errorf("calling to ProjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Project.
func (c *ProjectClient) Update() *ProjectUpdate {
	mutation := newProjectMutation(c.config, OpUpdate)
	return &ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectClient) UpdateOne(_m *Project) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProject(_m))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectClient) UpdateOneID(id int) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProjectID(id))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Project.
func (c *ProjectClient) Delete() *ProjectDelete {
	mutation := newProjectMutation(c.config, OpDelete)
	return &ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectClient) DeleteOne(_m *Project) *ProjectDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectClient) DeleteOneID(id int) *ProjectDeleteOne {
	builder := c.Delete().Where(project.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectDeleteOne{builder}
}

// Query returns a query builder for Project.
func (c *ProjectClient) Query() *ProjectQuery {
	return &ProjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProject},
		inters: c.Interceptors(),
	}
}

// Get returns a Project entity by its id.
func (c *ProjectClient) Get(ctx context.Context, id int) (*Project, error) {
	return c.Query().Where(project.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectClient) GetX(ctx context.Context, id int) *Project {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLabelRules queries the label_rules edge of a Project.
func (c *ProjectClient) QueryLabelRules(_m *Project) *ProjectLabelRuleQuery {
	query := (&ProjectLabelRuleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(projectlabelrule.Table, projectlabelrule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, project.LabelRulesTable, project.LabelRulesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTasks queries the tasks edge of a Project.
func (c *ProjectClient) QueryTasks(_m *Project) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, project.TasksTable, project.TasksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProjectClient) Hooks() []Hook {
	return c.hooks.Project
}

// Interceptors returns the client interceptors.
func (c *ProjectClient) Interceptors() []Interceptor {
	return c.inters.Project
}

func (c *ProjectClient) mutate(ctx context.Context, m *ProjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Project mutation op: %q", m.Op())
	}
}

// ProjectLabelRuleClient is a client for the ProjectLabelRule schema.
type ProjectLabelRuleClient struct {
	config
}

// NewProjectLabelRuleClient returns a client for the ProjectLabelRule from the given config.
func NewProjectLabelRuleClient(c config) *ProjectLabelRuleClient {
	return &ProjectLabelRuleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `projectlabelrule.Hooks(f(g(h())))`.
func (c *ProjectLabelRuleClient) Use(hooks ...Hook) {
	c.hooks.ProjectLabelRule = append(c.hooks.ProjectLabelRule, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `projectlabelrule.Intercept(f(g(h())))`.
func (c *ProjectLabelRuleClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProjectLabelRule = append(c.inters.ProjectLabelRule, interceptors...)
}

// Create returns a builder for creating a ProjectLabelRule entity.
func (c *ProjectLabelRuleClient) Create() *ProjectLabelRuleCreate {
	mutation := newProjectLabelRuleMutation(c.config, OpCreate)
	return &ProjectLabelRuleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProjectLabelRule entities.
func (c *ProjectLabelRuleClient) CreateBulk(builders ...*ProjectLabelRuleCreate) *ProjectLabelRuleCreateBulk {
	return &ProjectLabelRuleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectLabelRuleClient) MapCreateBulk(slice any, setFunc func(*ProjectLabelRuleCreate, int)) *ProjectLabelRuleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectLabelRuleCreateBulk{err: fmt.Errorf("calling to ProjectLabelRuleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectLabelRuleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectLabelRuleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProjectLabelRule.
func (c *ProjectLabelRuleClient) Update() *ProjectLabelRuleUpdate {
	mutation := newProjectLabelRuleMutation(c.config, OpUpdate)
	return &ProjectLabelRuleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectLabelRuleClient) UpdateOne(_m *ProjectLabelRule) *ProjectLabelRuleUpdateOne {
	mutation := newProjectLabelRuleMutation(c.config, OpUpdateOne, withProjectLabelRule(_m))
	return &ProjectLabelRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectLabelRuleClient) UpdateOneID(id int) *ProjectLabelRuleUpdateOne {
	mutation := newProjectLabelRuleMutation(c.config, OpUpdateOne, withProjectLabelRuleID(id))
	return &ProjectLabelRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProjectLabelRule.
func (c *ProjectLabelRuleClient) Delete() *ProjectLabelRuleDelete {
	mutation := newProjectLabelRuleMutation(c.config, OpDelete)
	return &ProjectLabelRuleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectLabelRuleClient) DeleteOne(_m *ProjectLabelRule) *ProjectLabelRuleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectLabelRuleClient) DeleteOneID(id int) *ProjectLabelRuleDeleteOne {
	builder := c.Delete().Where(projectlabelrule.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectLabelRuleDeleteOne{builder}
}

// Query returns a query builder for ProjectLabelRule.
func (c *ProjectLabelRuleClient) Query() *ProjectLabelRuleQuery {
	return &ProjectLabelRuleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProjectLabelRule},
		inters: c.Interceptors(),
	}
}

// Get returns a ProjectLabelRule entity by its id.
func (c *ProjectLabelRuleClient) Get(ctx context.Context, id int) (*ProjectLabelRule, error) {
	return c.Query().Where(projectlabelrule.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectLabelRuleClient) GetX(ctx context.Context, id int) *ProjectLabelRule {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a ProjectLabelRule.
func (c *ProjectLabelRuleClient) QueryProject(_m *ProjectLabelRule) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(projectlabelrule.Table, projectlabelrule.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projectlabelrule.ProjectTable, projectlabelrule.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPromptTemplate queries the prompt_template edge of a ProjectLabelRule.
func (c *ProjectLabelRuleClient) QueryPromptTemplate(_m *ProjectLabelRule) *PromptTemplateQuery {
	query := (&PromptTemplateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(projectlabelrule.Table, projectlabelrule.FieldID, id),
			sqlgraph.To(prompttemplate.Table, prompttemplate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, projectlabelrule.PromptTemplateTable, projectlabelrule.PromptTemplateColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProjectLabelRuleClient) Hooks() []Hook {
	return c.hooks.ProjectLabelRule
}

// Interceptors returns the client interceptors.
func (c *ProjectLabelRuleClient) Interceptors() []Interceptor {
	return c.inters.ProjectLabelRule
}

func (c *ProjectLabelRuleClient) mutate(ctx context.Context, m *ProjectLabelRuleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectLabelRuleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectLabelRuleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectLabelRuleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectLabelRuleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProjectLabelRule mutation op: %q", m.Op())
	}
}

// PromptTemplateClient is a client for the PromptTemplate schema.
type PromptTemplateClient struct {
	config
}

// NewPromptTemplateClient returns a client for the PromptTemplate from the given config.
func NewPromptTemplateClient(c config) *PromptTemplateClient {
	return &PromptTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `prompttemplate.Hooks(f(g(h())))`.
func (c *PromptTemplateClient) Use(hooks ...Hook) {
	c.hooks.PromptTemplate = append(c.hooks.PromptTemplate, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `prompttemplate.Intercept(f(g(h())))`.
func (c *PromptTemplateClient) Intercept(interceptors ...Interceptor) {
	c.inters.PromptTemplate = append(c.inters.PromptTemplate, interceptors...)
}

// Create returns a builder for creating a PromptTemplate entity.
func (c *PromptTemplateClient) Create() *PromptTemplateCreate {
	mutation := newPromptTemplateMutation(c.config, OpCreate)
	return &PromptTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PromptTemplate entities.
func (c *PromptTemplateClient) CreateBulk(builders ...*PromptTemplateCreate) *PromptTemplateCreateBulk {
	return &PromptTemplateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PromptTemplateClient) MapCreateBulk(slice any, setFunc func(*PromptTemplateCreate, int)) *PromptTemplateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PromptTemplateCreateBulk{err: fmt.Errorf("calling to PromptTemplateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PromptTemplateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PromptTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PromptTemplate.
func (c *PromptTemplateClient) Update() *PromptTemplateUpdate {
	mutation := newPromptTemplateMutation(c.config, OpUpdate)
	return &PromptTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PromptTemplateClient) UpdateOne(_m *PromptTemplate) *PromptTemplateUpdateOne {
	mutation := newPromptTemplateMutation(c.config, OpUpdateOne, withPromptTemplate(_m))
	return &PromptTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PromptTemplateClient) UpdateOneID(id int) *PromptTemplateUpdateOne {
	mutation := newPromptTemplateMutation(c.config, OpUpdateOne, withPromptTemplateID(id))
	return &PromptTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PromptTemplate.
func (c *PromptTemplateClient) Delete() *PromptTemplateDelete {
	mutation := newPromptTemplateMutation(c.config, OpDelete)
	return &PromptTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PromptTemplateClient) DeleteOne(_m *PromptTemplate) *PromptTemplateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PromptTemplateClient) DeleteOneID(id int) *PromptTemplateDeleteOne {
	builder := c.Delete().Where(prompttemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PromptTemplateDeleteOne{builder}
}

// Query returns a query builder for PromptTemplate.
func (c *PromptTemplateClient) Query() *PromptTemplateQuery {
	return &PromptTemplateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePromptTemplate},
		inters: c.Interceptors(),
	}
}

// Get returns a PromptTemplate entity by its id.
func (c *PromptTemplateClient) Get(ctx context.Context, id int) (*PromptTemplate, error) {
	return c.Query().Where(prompttemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PromptTemplateClient) GetX(ctx context.Context, id int) *PromptTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLabelRules queries the label_rules edge of a PromptTemplate.
func (c *PromptTemplateClient) QueryLabelRules(_m *PromptTemplate) *ProjectLabelRuleQuery {
	query := (&ProjectLabelRuleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(prompttemplate.Table, prompttemplate.FieldID, id),
			sqlgraph.To(projectlabelrule.Table, projectlabelrule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, prompttemplate.LabelRulesTable, prompttemplate.LabelRulesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PromptTemplateClient) Hooks() []Hook {
	return c.hooks.PromptTemplate
}

// Interceptors returns the client interceptors.
func (c *PromptTemplateClient) Interceptors() []Interceptor {
	return c.inters.PromptTemplate
}

func (c *PromptTemplateClient) mutate(ctx context.Context, m *PromptTemplateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PromptTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PromptTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PromptTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PromptTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PromptTemplate mutation op: %q", m.Op())
	}
}

// PromptTemplateSnapshotClient is a client for the PromptTemplateSnapshot schema.
type PromptTemplateSnapshotClient struct {
	config
}

// NewPromptTemplateSnapshotClient returns a client for the PromptTemplateSnapshot from the given config.
func NewPromptTemplateSnapshotClient(c config) *PromptTemplateSnapshotClient {
	return &PromptTemplateSnapshotClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `prompttemplatesnapshot.Hooks(f(g(h())))`.
func (c *PromptTemplateSnapshotClient) Use(hooks ...Hook) {
	c.hooks.PromptTemplateSnapshot = append(c.hooks.PromptTemplateSnapshot, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `prompttemplatesnapshot.Intercept(f(g(h())))`.
func (c *PromptTemplateSnapshotClient) Intercept(interceptors ...Interceptor) {
	c.inters.PromptTemplateSnapshot = append(c.inters.PromptTemplateSnapshot, interceptors...)
}

// Create returns a builder for creating a PromptTemplateSnapshot entity.
func (c *PromptTemplateSnapshotClient) Create() *PromptTemplateSnapshotCreate {
	mutation := newPromptTemplateSnapshotMutation(c.config, OpCreate)
	return &PromptTemplateSnapshotCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PromptTemplateSnapshot entities.
func (c *PromptTemplateSnapshotClient) CreateBulk(builders ...*PromptTemplateSnapshotCreate) *PromptTemplateSnapshotCreateBulk {
	return &PromptTemplateSnapshotCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PromptTemplateSnapshotClient) MapCreateBulk(slice any, setFunc func(*PromptTemplateSnapshotCreate, int)) *PromptTemplateSnapshotCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PromptTemplateSnapshotCreateBulk{err: fmt.Errorf("calling to PromptTemplateSnapshotClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PromptTemplateSnapshotCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PromptTemplateSnapshotCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PromptTemplateSnapshot.
func (c *PromptTemplateSnapshotClient) Update() *PromptTemplateSnapshotUpdate {
	mutation := newPromptTemplateSnapshotMutation(c.config, OpUpdate)
	return &PromptTemplateSnapshotUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PromptTemplateSnapshotClient) UpdateOne(_m *PromptTemplateSnapshot) *PromptTemplateSnapshotUpdateOne {
	mutation := newPromptTemplateSnapshotMutation(c.config, OpUpdateOne, withPromptTemplateSnapshot(_m))
	return &PromptTemplateSnapshotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PromptTemplateSnapshotClient) UpdateOneID(id int) *PromptTemplateSnapshotUpdateOne {
	mutation := newPromptTemplateSnapshotMutation(c.config, OpUpdateOne, withPromptTemplateSnapshotID(id))
	return &PromptTemplateSnapshotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PromptTemplateSnapshot.
func (c *PromptTemplateSnapshotClient) Delete() *PromptTemplateSnapshotDelete {
	mutation := newPromptTemplateSnapshotMutation(c.config, OpDelete)
	return &PromptTemplateSnapshotDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PromptTemplateSnapshotClient) DeleteOne(_m *PromptTemplateSnapshot) *PromptTemplateSnapshotDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PromptTemplateSnapshotClient) DeleteOneID(id int) *PromptTemplateSnapshotDeleteOne {
	builder := c.Delete().Where(prompttemplatesnapshot.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PromptTemplateSnapshotDeleteOne{builder}
}

// Query returns a query builder for PromptTemplateSnapshot.
func (c *PromptTemplateSnapshotClient) Query() *PromptTemplateSnapshotQuery {
	return &PromptTemplateSnapshotQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePromptTemplateSnapshot},
		inters: c.Interceptors(),
	}
}

// Get returns a PromptTemplateSnapshot entity by its id.
func (c *PromptTemplateSnapshotClient) Get(ctx context.Context, id int) (*PromptTemplateSnapshot, error) {
	return c.Query().Where(prompttemplatesnapshot.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PromptTemplateSnapshotClient) GetX(ctx context.Context, id int) *PromptTemplateSnapshot {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a PromptTemplateSnapshot.
func (c *PromptTemplateSnapshotClient) QueryTask(_m *PromptTemplateSnapshot) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(prompttemplatesnapshot.Table, prompttemplatesnapshot.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, prompttemplatesnapshot.TaskTable, prompttemplatesnapshot.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PromptTemplateSnapshotClient) Hooks() []Hook {
	return c.hooks.PromptTemplateSnapshot
}

// Interceptors returns the client interceptors.
func (c *PromptTemplateSnapshotClient) Interceptors() []Interceptor {
	return c.inters.PromptTemplateSnapshot
}

func (c *PromptTemplateSnapshotClient) mutate(ctx context.Context, m *PromptTemplateSnapshotMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PromptTemplateSnapshotCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PromptTemplateSnapshotUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PromptTemplateSnapshotUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PromptTemplateSnapshotDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PromptTemplateSnapshot mutation op: %q", m.Op())
	}
}

// SessionClient is a client for the Session schema.
type SessionClient struct {
	config
}

// NewSessionClient returns a client for the Session from the given config.
func NewSessionClient(c config) *SessionClient {
	return &SessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `session.Hooks(f(g(h())))`.
func (c *SessionClient) Use(hooks ...Hook) {
	c.hooks.Session = append(c.hooks.Session, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `session.Intercept(f(g(h())))`.
func (c *SessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Session = append(c.inters.Session, interceptors...)
}

// Create returns a builder for creating a Session entity.
func (c *SessionClient) Create() *SessionCreate {
	mutation := newSessionMutation(c.config, OpCreate)
	return &SessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Session entities.
func (c *SessionClient) CreateBulk(builders ...*SessionCreate) *SessionCreateBulk {
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionClient) MapCreateBulk(slice any, setFunc func(*SessionCreate, int)) *SessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionCreateBulk{err: fmt.Errorf("calling to SessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Session.
func (c *SessionClient) Update() *SessionUpdate {
	mutation := newSessionMutation(c.config, OpUpdate)
	return &SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionClient) UpdateOne(_m *Session) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSession(_m))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionClient) UpdateOneID(id int) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSessionID(id))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Session.
func (c *SessionClient) Delete() *SessionDelete {
	mutation := newSessionMutation(c.config, OpDelete)
	return &SessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionClient) DeleteOne(_m *Session) *SessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionClient) DeleteOneID(id int) *SessionDeleteOne {
	builder := c.Delete().Where(session.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionDeleteOne{builder}
}

// Query returns a query builder for Session.
func (c *SessionClient) Query() *SessionQuery {
	return &SessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSession},
		inters: c.Interceptors(),
	}
}

// Get returns a Session entity by its id.
func (c *SessionClient) Get(ctx context.Context, id int) (*Session, error) {
	return c.Query().Where(session.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionClient) GetX(ctx context.Context, id int) *Session {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTask queries the task edge of a Session.
func (c *SessionClient) QueryTask(_m *Session) *TaskQuery {
	query := (&TaskClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, session.TaskTable, session.TaskColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMessages queries the messages edge of a Session.
func (c *SessionClient) QueryMessages(_m *Session) *SessionMessageQuery {
	query := (&SessionMessageClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(sessionmessage.Table, sessionmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.MessagesTable, session.MessagesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEvents queries the events edge of a Session.
func (c *SessionClient) QueryEvents(_m *Session) *SessionEventQuery {
	query := (&SessionEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(sessionevent.Table, sessionevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.EventsTable, session.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionClient) Hooks() []Hook {
	return c.hooks.Session
}

// Interceptors returns the client interceptors.
func (c *SessionClient) Interceptors() []Interceptor {
	return c.inters.Session
}

func (c *SessionClient) mutate(ctx context.Context, m *SessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Session mutation op: %q", m.Op())
	}
}

// SessionEventClient is a client for the SessionEvent schema.
type SessionEventClient struct {
	config
}

// NewSessionEventClient returns a client for the SessionEvent from the given config.
func NewSessionEventClient(c config) *SessionEventClient {
	return &SessionEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sessionevent.Hooks(f(g(h())))`.
func (c *SessionEventClient) Use(hooks ...Hook) {
	c.hooks.SessionEvent = append(c.hooks.SessionEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sessionevent.Intercept(f(g(h())))`.
func (c *SessionEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.SessionEvent = append(c.inters.SessionEvent, interceptors...)
}

// Create returns a builder for creating a SessionEvent entity.
func (c *SessionEventClient) Create() *SessionEventCreate {
	mutation := newSessionEventMutation(c.config, OpCreate)
	return &SessionEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SessionEvent entities.
func (c *SessionEventClient) CreateBulk(builders ...*SessionEventCreate) *SessionEventCreateBulk {
	return &SessionEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionEventClient) MapCreateBulk(slice any, setFunc func(*SessionEventCreate, int)) *SessionEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionEventCreateBulk{err: fmt.Errorf("calling to SessionEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SessionEvent.
func (c *SessionEventClient) Update() *SessionEventUpdate {
	mutation := newSessionEventMutation(c.config, OpUpdate)
	return &SessionEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionEventClient) UpdateOne(_m *SessionEvent) *SessionEventUpdateOne {
	mutation := newSessionEventMutation(c.config, OpUpdateOne, withSessionEvent(_m))
	return &SessionEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionEventClient) UpdateOneID(id int) *SessionEventUpdateOne {
	mutation := newSessionEventMutation(c.config, OpUpdateOne, withSessionEventID(id))
	return &SessionEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SessionEvent.
func (c *SessionEventClient) Delete() *SessionEventDelete {
	mutation := newSessionEventMutation(c.config, OpDelete)
	return &SessionEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionEventClient) DeleteOne(_m *SessionEvent) *SessionEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionEventClient) DeleteOneID(id int) *SessionEventDeleteOne {
	builder := c.Delete().Where(sessionevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionEventDeleteOne{builder}
}

// Query returns a query builder for SessionEvent.
func (c *SessionEventClient) Query() *SessionEventQuery {
	return &SessionEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSessionEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a SessionEvent entity by its id.
func (c *SessionEventClient) Get(ctx context.Context, id int) (*SessionEvent, error) {
	return c.Query().Where(sessionevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionEventClient) GetX(ctx context.Context, id int) *SessionEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a SessionEvent.
func (c *SessionEventClient) QuerySession(_m *SessionEvent) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sessionevent.Table, sessionevent.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sessionevent.SessionTable, sessionevent.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionEventClient) Hooks() []Hook {
	return c.hooks.SessionEvent
}

// Interceptors returns the client interceptors.
func (c *SessionEventClient) Interceptors() []Interceptor {
	return c.inters.SessionEvent
}

func (c *SessionEventClient) mutate(ctx context.Context, m *SessionEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SessionEvent mutation op: %q", m.Op())
	}
}

// SessionMessageClient is a client for the SessionMessage schema.
type SessionMessageClient struct {
	config
}

// NewSessionMessageClient returns a client for the SessionMessage from the given config.
func NewSessionMessageClient(c config) *SessionMessageClient {
	return &SessionMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sessionmessage.Hooks(f(g(h())))`.
func (c *SessionMessageClient) Use(hooks ...Hook) {
	c.hooks.SessionMessage = append(c.hooks.SessionMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sessionmessage.Intercept(f(g(h())))`.
func (c *SessionMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.SessionMessage = append(c.inters.SessionMessage, interceptors...)
}

// Create returns a builder for creating a SessionMessage entity.
func (c *SessionMessageClient) Create() *SessionMessageCreate {
	mutation := newSessionMessageMutation(c.config, OpCreate)
	return &SessionMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SessionMessage entities.
func (c *SessionMessageClient) CreateBulk(builders ...*SessionMessageCreate) *SessionMessageCreateBulk {
	return &SessionMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionMessageClient) MapCreateBulk(slice any, setFunc func(*SessionMessageCreate, int)) *SessionMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionMessageCreateBulk{err: fmt.Errorf("calling to SessionMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SessionMessage.
func (c *SessionMessageClient) Update() *SessionMessageUpdate {
	mutation := newSessionMessageMutation(c.config, OpUpdate)
	return &SessionMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionMessageClient) UpdateOne(_m *SessionMessage) *SessionMessageUpdateOne {
	mutation := newSessionMessageMutation(c.config, OpUpdateOne, withSessionMessage(_m))
	return &SessionMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionMessageClient) UpdateOneID(id int) *SessionMessageUpdateOne {
	mutation := newSessionMessageMutation(c.config, OpUpdateOne, withSessionMessageID(id))
	return &SessionMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SessionMessage.
func (c *SessionMessageClient) Delete() *SessionMessageDelete {
	mutation := newSessionMessageMutation(c.config, OpDelete)
	return &SessionMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionMessageClient) DeleteOne(_m *SessionMessage) *SessionMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionMessageClient) DeleteOneID(id int) *SessionMessageDeleteOne {
	builder := c.Delete().Where(sessionmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionMessageDeleteOne{builder}
}

// Query returns a query builder for SessionMessage.
func (c *SessionMessageClient) Query() *SessionMessageQuery {
	return &SessionMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSessionMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a SessionMessage entity by its id.
func (c *SessionMessageClient) Get(ctx context.Context, id int) (*SessionMessage, error) {
	return c.Query().Where(sessionmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionMessageClient) GetX(ctx context.Context, id int) *SessionMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a SessionMessage.
func (c *SessionMessageClient) QuerySession(_m *SessionMessage) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sessionmessage.Table, sessionmessage.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sessionmessage.SessionTable, sessionmessage.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAttachments queries the attachments edge of a SessionMessage.
func (c *SessionMessageClient) QueryAttachments(_m *SessionMessage) *AttachmentQuery {
	query := (&AttachmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sessionmessage.Table, sessionmessage.FieldID, id),
			sqlgraph.To(attachment.Table, attachment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, sessionmessage.AttachmentsTable, sessionmessage.AttachmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionMessageClient) Hooks() []Hook {
	return c.hooks.SessionMessage
}

// Interceptors returns the client interceptors.
func (c *SessionMessageClient) Interceptors() []Interceptor {
	return c.inters.SessionMessage
}

func (c *SessionMessageClient) mutate(ctx context.Context, m *SessionMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SessionMessage mutation op: %q", m.Op())
	}
}

// SystemSettingClient is a client for the SystemSetting schema.
type SystemSettingClient struct {
	config
}

// NewSystemSettingClient returns a client for the SystemSetting from the given config.
func NewSystemSettingClient(c config) *SystemSettingClient {
	return &SystemSettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `systemsetting.Hooks(f(g(h())))`.
func (c *SystemSettingClient) Use(hooks ...Hook) {
	c.hooks.SystemSetting = append(c.hooks.SystemSetting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `systemsetting.Intercept(f(g(h())))`.
func (c *SystemSettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.SystemSetting = append(c.inters.SystemSetting, interceptors...)
}

// Create returns a builder for creating a SystemSetting entity.
func (c *SystemSettingClient) Create() *SystemSettingCreate {
	mutation := newSystemSettingMutation(c.config, OpCreate)
	return &SystemSettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SystemSetting entities.
func (c *SystemSettingClient) CreateBulk(builders ...*SystemSettingCreate) *SystemSettingCreateBulk {
	return &SystemSettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SystemSettingClient) MapCreateBulk(slice any, setFunc func(*SystemSettingCreate, int)) *SystemSettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SystemSettingCreateBulk{err: fmt.Errorf("calling to SystemSettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SystemSettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SystemSettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SystemSetting.
func (c *SystemSettingClient) Update() *SystemSettingUpdate {
	mutation := newSystemSettingMutation(c.config, OpUpdate)
	return &SystemSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SystemSettingClient) UpdateOne(_m *SystemSetting) *SystemSettingUpdateOne {
	mutation := newSystemSettingMutation(c.config, OpUpdateOne, withSystemSetting(_m))
	return &SystemSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SystemSettingClient) UpdateOneID(id int) *SystemSettingUpdateOne {
	mutation := newSystemSettingMutation(c.config, OpUpdateOne, withSystemSettingID(id))
	return &SystemSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SystemSetting.
func (c *SystemSettingClient) Delete() *SystemSettingDelete {
	mutation := newSystemSettingMutation(c.config, OpDelete)
	return &SystemSettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SystemSettingClient) DeleteOne(_m *SystemSetting) *SystemSettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SystemSettingClient) DeleteOneID(id int) *SystemSettingDeleteOne {
	builder := c.Delete().Where(systemsetting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SystemSettingDeleteOne{builder}
}

// Query returns a query builder for SystemSetting.
func (c *SystemSettingClient) Query() *SystemSettingQuery {
	return &SystemSettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSystemSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a SystemSetting entity by its id.
func (c *SystemSettingClient) Get(ctx context.Context, id int) (*SystemSetting, error) {
	return c.Query().Where(systemsetting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SystemSettingClient) GetX(ctx context.Context, id int) *SystemSetting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SystemSettingClient) Hooks() []Hook {
	return c.hooks.SystemSetting
}

// Interceptors returns the client interceptors.
func (c *SystemSettingClient) Interceptors() []Interceptor {
	return c.inters.SystemSetting
}

func (c *SystemSettingClient) mutate(ctx context.Context, m *SystemSettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SystemSettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SystemSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SystemSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SystemSettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SystemSetting mutation op: %q", m.Op())
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id int) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id int) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id int) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id int) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a Task.
func (c *TaskClient) QueryProject(_m *Task) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, task.ProjectTable, task.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySessions queries the sessions edge of a Task.
func (c *TaskClient) QuerySessions(_m *Task) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.SessionsTable, task.SessionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPromptSnapshot queries the prompt_snapshot edge of a Task.
func (c *TaskClient) QueryPromptSnapshot(_m *Task) *PromptTemplateSnapshotQuery {
	query := (&PromptTemplateSnapshotClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(prompttemplatesnapshot.Table, prompttemplatesnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, task.PromptSnapshotTable, task.PromptSnapshotColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAttachments queries the attachments edge of a Task.
func (c *TaskClient) QueryAttachments(_m *Task) *AttachmentQuery {
	query := (&AttachmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(attachment.Table, attachment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.AttachmentsTable, task.AttachmentsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCommandAudits queries the command_audits edge of a Task.
func (c *TaskClient) QueryCommandAudits(_m *Task) *CommandAuditQuery {
	query := (&CommandAuditClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(commandaudit.Table, commandaudit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, task.CommandAuditsTable, task.CommandAuditsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryExecutionLease queries the execution_lease edge of a Task.
func (c *TaskClient) QueryExecutionLease(_m *Task) *ExecutionLeaseQuery {
	query := (&ExecutionLeaseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(executionlease.Table, executionlease.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, task.ExecutionLeaseTable, task.ExecutionLeaseColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Task mutation op: %q", m.Op())
	}
}

// WebhookReceiptClient is a client for the WebhookReceipt schema.
type WebhookReceiptClient struct {
	config
}

// NewWebhookReceiptClient returns a client for the WebhookReceipt from the given config.
func NewWebhookReceiptClient(c config) *WebhookReceiptClient {
	return &WebhookReceiptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `webhookreceipt.Hooks(f(g(h())))`.
func (c *WebhookReceiptClient) Use(hooks ...Hook) {
	c.hooks.WebhookReceipt = append(c.hooks.WebhookReceipt, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `webhookreceipt.Intercept(f(g(h())))`.
func (c *WebhookReceiptClient) Intercept(interceptors ...Interceptor) {
	c.inters.WebhookReceipt = append(c.inters.WebhookReceipt, interceptors...)
}

// Create returns a builder for creating a WebhookReceipt entity.
func (c *WebhookReceiptClient) Create() *WebhookReceiptCreate {
	mutation := newWebhookReceiptMutation(c.config, OpCreate)
	return &WebhookReceiptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WebhookReceipt entities.
func (c *WebhookReceiptClient) CreateBulk(builders ...*WebhookReceiptCreate) *WebhookReceiptCreateBulk {
	return &WebhookReceiptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WebhookReceiptClient) MapCreateBulk(slice any, setFunc func(*WebhookReceiptCreate, int)) *WebhookReceiptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WebhookReceiptCreateBulk{err: fmt.Errorf("calling to WebhookReceiptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WebhookReceiptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WebhookReceiptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WebhookReceipt.
func (c *WebhookReceiptClient) Update() *WebhookReceiptUpdate {
	mutation := newWebhookReceiptMutation(c.config, OpUpdate)
	return &WebhookReceiptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WebhookReceiptClient) UpdateOne(_m *WebhookReceipt) *WebhookReceiptUpdateOne {
	mutation := newWebhookReceiptMutation(c.config, OpUpdateOne, withWebhookReceipt(_m))
	return &WebhookReceiptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WebhookReceiptClient) UpdateOneID(id int) *WebhookReceiptUpdateOne {
	mutation := newWebhookReceiptMutation(c.config, OpUpdateOne, withWebhookReceiptID(id))
	return &WebhookReceiptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WebhookReceipt.
func (c *WebhookReceiptClient) Delete() *WebhookReceiptDelete {
	mutation := newWebhookReceiptMutation(c.config, OpDelete)
	return &WebhookReceiptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WebhookReceiptClient) DeleteOne(_m *WebhookReceipt) *WebhookReceiptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WebhookReceiptClient) DeleteOneID(id int) *WebhookReceiptDeleteOne {
	builder := c.Delete().Where(webhookreceipt.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WebhookReceiptDeleteOne{builder}
}

// Query returns a query builder for WebhookReceipt.
func (c *WebhookReceiptClient) Query() *WebhookReceiptQuery {
	return &WebhookReceiptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWebhookReceipt},
		inters: c.Interceptors(),
	}
}

// Get returns a WebhookReceipt entity by its id.
func (c *WebhookReceiptClient) Get(ctx context.Context, id int) (*WebhookReceipt, error) {
	return c.Query().Where(webhookreceipt.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WebhookReceiptClient) GetX(ctx context.Context, id int) *WebhookReceipt {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WebhookReceiptClient) Hooks() []Hook {
	return c.hooks.WebhookReceipt
}

// Interceptors returns the client interceptors.
func (c *WebhookReceiptClient) Interceptors() []Interceptor {
	return c.inters.WebhookReceipt
}

func (c *WebhookReceiptClient) mutate(ctx context.Context, m *WebhookReceiptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WebhookReceiptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WebhookReceiptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WebhookReceiptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WebhookReceiptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WebhookReceipt mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AgentProfile, Attachment, CommandAudit, ExecutionLease, Project,
		ProjectLabelRule, PromptTemplate, PromptTemplateSnapshot, Session,
		SessionEvent, SessionMessage, SystemSetting, Task, WebhookReceipt []ent.Hook
	}
	inters struct {
		AgentProfile, Attachment, CommandAudit, ExecutionLease, Project,
		ProjectLabelRule, PromptTemplate, PromptTemplateSnapshot, Session,
		SessionEvent, SessionMessage, SystemSetting, Task,
		WebhookReceipt []ent.Interceptor
	}
)
