// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/commandaudit"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
)

// CommandAuditDelete is the builder for deleting a CommandAudit entity.
type CommandAuditDelete struct {
	config
	hooks    []Hook
	mutation *CommandAuditMutation
}

// Where appends a list predicates to the CommandAuditDelete builder.
func (_d *CommandAuditDelete) Where(ps ...predicate.CommandAudit) *CommandAuditDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CommandAuditDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CommandAuditDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CommandAuditDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(commandaudit.Table, sqlgraph.NewFieldSpec(commandaudit.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CommandAuditDeleteOne is the builder for deleting a single CommandAudit entity.
type CommandAuditDeleteOne struct {
	_d *CommandAuditDelete
}

// Where appends a list predicates to the CommandAuditDelete builder.
func (_d *CommandAuditDeleteOne) Where(ps ...predicate.CommandAudit) *CommandAuditDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CommandAuditDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{commandaudit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CommandAuditDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
