// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/commandaudit"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
	"github.com/cloverstd/ccmate/internal/ent/task"
)

// CommandAuditUpdate is the builder for updating CommandAudit entities.
type CommandAuditUpdate struct {
	config
	hooks    []Hook
	mutation *CommandAuditMutation
}

// Where appends a list predicates to the CommandAuditUpdate builder.
func (_u *CommandAuditUpdate) Where(ps ...predicate.CommandAudit) *CommandAuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *CommandAuditUpdate) SetSource(v string) *CommandAuditUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CommandAuditUpdate) SetNillableSource(v *string) *CommandAuditUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *CommandAuditUpdate) SetActor(v string) *CommandAuditUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *CommandAuditUpdate) SetNillableActor(v *string) *CommandAuditUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *CommandAuditUpdate) SetCommand(v string) *CommandAuditUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *CommandAuditUpdate) SetNillableCommand(v *string) *CommandAuditUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetDecision sets the "decision" field.
func (_u *CommandAuditUpdate) SetDecision(v commandaudit.Decision) *CommandAuditUpdate {
	_u.mutation.SetDecision(v)
	return _u
}

// SetNillableDecision sets the "decision" field if the given value is not nil.
func (_u *CommandAuditUpdate) SetNillableDecision(v *commandaudit.Decision) *CommandAuditUpdate {
	if v != nil {
		_u.SetDecision(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *CommandAuditUpdate) SetReason(v string) *CommandAuditUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CommandAuditUpdate) SetNillableReason(v *string) *CommandAuditUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *CommandAuditUpdate) SetTaskID(id int) *CommandAuditUpdate {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetNillableTaskID sets the "task" edge to the Task entity by ID if the given value is not nil.
func (_u *CommandAuditUpdate) SetNillableTaskID(id *int) *CommandAuditUpdate {
	if id != nil {
		_u = _u.SetTaskID(*id)
	}
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *CommandAuditUpdate) SetTask(v *Task) *CommandAuditUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the CommandAuditMutation object of the builder.
func (_u *CommandAuditUpdate) Mutation() *CommandAuditMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *CommandAuditUpdate) ClearTask() *CommandAuditUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommandAuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommandAuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommandAuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommandAuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommandAuditUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := commandaudit.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CommandAudit.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Actor(); ok {
		if err := commandaudit.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "CommandAudit.actor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Command(); ok {
		if err := commandaudit.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`ent: validator failed for field "CommandAudit.command": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Decision(); ok {
		if err := commandaudit.DecisionValidator(v); err != nil {
			return &ValidationError{Name: "decision", err: fmt.Errorf(`ent: validator failed for field "CommandAudit.decision": %w`, err)}
		}
	}
	return nil
}

func (_u *CommandAuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commandaudit.Table, commandaudit.Columns, sqlgraph.NewFieldSpec(commandaudit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(commandaudit.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(commandaudit.FieldActor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(commandaudit.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Decision(); ok {
		_spec.SetField(commandaudit.FieldDecision, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(commandaudit.FieldReason, field.TypeString, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandaudit.TaskTable,
			Columns: []string{commandaudit.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandaudit.TaskTable,
			Columns: []string{commandaudit.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commandaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommandAuditUpdateOne is the builder for updating a single CommandAudit entity.
type CommandAuditUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommandAuditMutation
}

// SetSource sets the "source" field.
func (_u *CommandAuditUpdateOne) SetSource(v string) *CommandAuditUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CommandAuditUpdateOne) SetNillableSource(v *string) *CommandAuditUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *CommandAuditUpdateOne) SetActor(v string) *CommandAuditUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *CommandAuditUpdateOne) SetNillableActor(v *string) *CommandAuditUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *CommandAuditUpdateOne) SetCommand(v string) *CommandAuditUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *CommandAuditUpdateOne) SetNillableCommand(v *string) *CommandAuditUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetDecision sets the "decision" field.
func (_u *CommandAuditUpdateOne) SetDecision(v commandaudit.Decision) *CommandAuditUpdateOne {
	_u.mutation.SetDecision(v)
	return _u
}

// SetNillableDecision sets the "decision" field if the given value is not nil.
func (_u *CommandAuditUpdateOne) SetNillableDecision(v *commandaudit.Decision) *CommandAuditUpdateOne {
	if v != nil {
		_u.SetDecision(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *CommandAuditUpdateOne) SetReason(v string) *CommandAuditUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *CommandAuditUpdateOne) SetNillableReason(v *string) *CommandAuditUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_u *CommandAuditUpdateOne) SetTaskID(id int) *CommandAuditUpdateOne {
	_u.mutation.SetTaskID(id)
	return _u
}

// SetNillableTaskID sets the "task" edge to the Task entity by ID if the given value is not nil.
func (_u *CommandAuditUpdateOne) SetNillableTaskID(id *int) *CommandAuditUpdateOne {
	if id != nil {
		_u = _u.SetTaskID(*id)
	}
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *CommandAuditUpdateOne) SetTask(v *Task) *CommandAuditUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the CommandAuditMutation object of the builder.
func (_u *CommandAuditUpdateOne) Mutation() *CommandAuditMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *CommandAuditUpdateOne) ClearTask() *CommandAuditUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the CommandAuditUpdate builder.
func (_u *CommandAuditUpdateOne) Where(ps ...predicate.CommandAudit) *CommandAuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommandAuditUpdateOne) Select(field string, fields ...string) *CommandAuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CommandAudit entity.
func (_u *CommandAuditUpdateOne) Save(ctx context.Context) (*CommandAudit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommandAuditUpdateOne) SaveX(ctx context.Context) *CommandAudit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommandAuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommandAuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CommandAuditUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := commandaudit.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "CommandAudit.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Actor(); ok {
		if err := commandaudit.ActorValidator(v); err != nil {
			return &ValidationError{Name: "actor", err: fmt.Errorf(`ent: validator failed for field "CommandAudit.actor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Command(); ok {
		if err := commandaudit.CommandValidator(v); err != nil {
			return &ValidationError{Name: "command", err: fmt.Errorf(`ent: validator failed for field "CommandAudit.command": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Decision(); ok {
		if err := commandaudit.DecisionValidator(v); err != nil {
			return &ValidationError{Name: "decision", err: fmt.Errorf(`ent: validator failed for field "CommandAudit.decision": %w`, err)}
		}
	}
	return nil
}

func (_u *CommandAuditUpdateOne) sqlSave(ctx context.Context) (_node *CommandAudit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commandaudit.Table, commandaudit.Columns, sqlgraph.NewFieldSpec(commandaudit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommandAudit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commandaudit.FieldID)
		for _, f := range fields {
			if !commandaudit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commandaudit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(commandaudit.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(commandaudit.FieldActor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(commandaudit.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Decision(); ok {
		_spec.SetField(commandaudit.FieldDecision, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(commandaudit.FieldReason, field.TypeString, value)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandaudit.TaskTable,
			Columns: []string{commandaudit.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandaudit.TaskTable,
			Columns: []string{commandaudit.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CommandAudit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commandaudit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
