// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/ccmate/internal/ent/executionlease"
	"github.com/cloverstd/ccmate/internal/ent/task"
)

// ExecutionLease is the model entity for the ExecutionLease schema.
type ExecutionLease struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RunnerID holds the value of the "runner_id" field.
	RunnerID string `json:"runner_id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExecutionLeaseQuery when eager-loading is set.
	Edges                ExecutionLeaseEdges `json:"edges"`
	task_execution_lease *int
	selectValues         sql.SelectValues
}

// ExecutionLeaseEdges holds the relations/edges for other nodes in the graph.
type ExecutionLeaseEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExecutionLeaseEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExecutionLease) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case executionlease.FieldID:
			values[i] = new(sql.NullInt64)
		case executionlease.FieldRunnerID:
			values[i] = new(sql.NullString)
		case executionlease.FieldStartedAt, executionlease.FieldExpiresAt, executionlease.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case executionlease.ForeignKeys[0]: // task_execution_lease
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExecutionLease fields.
func (_m *ExecutionLease) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case executionlease.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case executionlease.FieldRunnerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field runner_id", values[i])
			} else if value.Valid {
				_m.RunnerID = value.String
			}
		case executionlease.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case executionlease.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case executionlease.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case executionlease.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field task_execution_lease", value)
			} else if value.Valid {
				_m.task_execution_lease = new(int)
				*_m.task_execution_lease = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExecutionLease.
// This includes values selected through modifiers, order, etc.
func (_m *ExecutionLease) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the ExecutionLease entity.
func (_m *ExecutionLease) QueryTask() *TaskQuery {
	return NewExecutionLeaseClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this ExecutionLease.
// Note that you need to call ExecutionLease.Unwrap() before calling this method if this ExecutionLease
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExecutionLease) Update() *ExecutionLeaseUpdateOne {
	return NewExecutionLeaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExecutionLease entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExecutionLease) Unwrap() *ExecutionLease {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExecutionLease is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExecutionLease) String() string {
	var builder strings.Builder
	builder.WriteString("ExecutionLease(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("runner_id=")
	builder.WriteString(_m.RunnerID)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ExecutionLeases is a parsable slice of ExecutionLease.
type ExecutionLeases []*ExecutionLease
