// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
	"github.com/cloverstd/ccmate/internal/ent/project"
	"github.com/cloverstd/ccmate/internal/ent/projectlabelrule"
	"github.com/cloverstd/ccmate/internal/ent/task"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdate) SetName(v string) *ProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *ProjectUpdate) SetRepoURL(v string) *ProjectUpdate {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableRepoURL(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// SetGitProvider sets the "git_provider" field.
func (_u *ProjectUpdate) SetGitProvider(v string) *ProjectUpdate {
	_u.mutation.SetGitProvider(v)
	return _u
}

// SetNillableGitProvider sets the "git_provider" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableGitProvider(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetGitProvider(*v)
	}
	return _u
}

// SetDefaultBranch sets the "default_branch" field.
func (_u *ProjectUpdate) SetDefaultBranch(v string) *ProjectUpdate {
	_u.mutation.SetDefaultBranch(v)
	return _u
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDefaultBranch(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetDefaultBranch(*v)
	}
	return _u
}

// SetAutoMode sets the "auto_mode" field.
func (_u *ProjectUpdate) SetAutoMode(v bool) *ProjectUpdate {
	_u.mutation.SetAutoMode(v)
	return _u
}

// SetNillableAutoMode sets the "auto_mode" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableAutoMode(v *bool) *ProjectUpdate {
	if v != nil {
		_u.SetAutoMode(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdate) SetUpdatedAt(v time.Time) *ProjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLabelRuleIDs adds the "label_rules" edge to the ProjectLabelRule entity by IDs.
func (_u *ProjectUpdate) AddLabelRuleIDs(ids ...int) *ProjectUpdate {
	_u.mutation.AddLabelRuleIDs(ids...)
	return _u
}

// AddLabelRules adds the "label_rules" edges to the ProjectLabelRule entity.
func (_u *ProjectUpdate) AddLabelRules(v ...*ProjectLabelRule) *ProjectUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelRuleIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *ProjectUpdate) AddTaskIDs(ids ...int) *ProjectUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *ProjectUpdate) AddTasks(v ...*Task) *ProjectUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearLabelRules clears all "label_rules" edges to the ProjectLabelRule entity.
func (_u *ProjectUpdate) ClearLabelRules() *ProjectUpdate {
	_u.mutation.ClearLabelRules()
	return _u
}

// RemoveLabelRuleIDs removes the "label_rules" edge to ProjectLabelRule entities by IDs.
func (_u *ProjectUpdate) RemoveLabelRuleIDs(ids ...int) *ProjectUpdate {
	_u.mutation.RemoveLabelRuleIDs(ids...)
	return _u
}

// RemoveLabelRules removes "label_rules" edges to ProjectLabelRule entities.
func (_u *ProjectUpdate) RemoveLabelRules(v ...*ProjectLabelRule) *ProjectUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelRuleIDs(ids...)
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *ProjectUpdate) ClearTasks() *ProjectUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *ProjectUpdate) RemoveTaskIDs(ids ...int) *ProjectUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *ProjectUpdate) RemoveTasks(v ...*Task) *ProjectUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoURL(); ok {
		if err := project.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "Project.repo_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(project.FieldRepoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitProvider(); ok {
		_spec.SetField(project.FieldGitProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultBranch(); ok {
		_spec.SetField(project.FieldDefaultBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.AutoMode(); ok {
		_spec.SetField(project.FieldAutoMode, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LabelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelRulesTable,
			Columns: []string{project.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelRulesIDs(); len(nodes) > 0 && !_u.mutation.LabelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelRulesTable,
			Columns: []string{project.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelRulesTable,
			Columns: []string{project.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetName sets the "name" field.
func (_u *ProjectUpdateOne) SetName(v string) *ProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *ProjectUpdateOne) SetRepoURL(v string) *ProjectUpdateOne {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableRepoURL(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// SetGitProvider sets the "git_provider" field.
func (_u *ProjectUpdateOne) SetGitProvider(v string) *ProjectUpdateOne {
	_u.mutation.SetGitProvider(v)
	return _u
}

// SetNillableGitProvider sets the "git_provider" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableGitProvider(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetGitProvider(*v)
	}
	return _u
}

// SetDefaultBranch sets the "default_branch" field.
func (_u *ProjectUpdateOne) SetDefaultBranch(v string) *ProjectUpdateOne {
	_u.mutation.SetDefaultBranch(v)
	return _u
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDefaultBranch(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetDefaultBranch(*v)
	}
	return _u
}

// SetAutoMode sets the "auto_mode" field.
func (_u *ProjectUpdateOne) SetAutoMode(v bool) *ProjectUpdateOne {
	_u.mutation.SetAutoMode(v)
	return _u
}

// SetNillableAutoMode sets the "auto_mode" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableAutoMode(v *bool) *ProjectUpdateOne {
	if v != nil {
		_u.SetAutoMode(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProjectUpdateOne) SetUpdatedAt(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLabelRuleIDs adds the "label_rules" edge to the ProjectLabelRule entity by IDs.
func (_u *ProjectUpdateOne) AddLabelRuleIDs(ids ...int) *ProjectUpdateOne {
	_u.mutation.AddLabelRuleIDs(ids...)
	return _u
}

// AddLabelRules adds the "label_rules" edges to the ProjectLabelRule entity.
func (_u *ProjectUpdateOne) AddLabelRules(v ...*ProjectLabelRule) *ProjectUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelRuleIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *ProjectUpdateOne) AddTaskIDs(ids ...int) *ProjectUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *ProjectUpdateOne) AddTasks(v ...*Task) *ProjectUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearLabelRules clears all "label_rules" edges to the ProjectLabelRule entity.
func (_u *ProjectUpdateOne) ClearLabelRules() *ProjectUpdateOne {
	_u.mutation.ClearLabelRules()
	return _u
}

// RemoveLabelRuleIDs removes the "label_rules" edge to ProjectLabelRule entities by IDs.
func (_u *ProjectUpdateOne) RemoveLabelRuleIDs(ids ...int) *ProjectUpdateOne {
	_u.mutation.RemoveLabelRuleIDs(ids...)
	return _u
}

// RemoveLabelRules removes "label_rules" edges to ProjectLabelRule entities.
func (_u *ProjectUpdateOne) RemoveLabelRules(v ...*ProjectLabelRule) *ProjectUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelRuleIDs(ids...)
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *ProjectUpdateOne) ClearTasks() *ProjectUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *ProjectUpdateOne) RemoveTaskIDs(ids ...int) *ProjectUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *ProjectUpdateOne) RemoveTasks(v ...*Task) *ProjectUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoURL(); ok {
		if err := project.RepoURLValidator(v); err != nil {
			return &ValidationError{Name: "repo_url", err: fmt.Errorf(`ent: validator failed for field "Project.repo_url": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(project.FieldRepoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.GitProvider(); ok {
		_spec.SetField(project.FieldGitProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultBranch(); ok {
		_spec.SetField(project.FieldDefaultBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.AutoMode(); ok {
		_spec.SetField(project.FieldAutoMode, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LabelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelRulesTable,
			Columns: []string{project.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelRulesIDs(); len(nodes) > 0 && !_u.mutation.LabelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelRulesTable,
			Columns: []string{project.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelRulesTable,
			Columns: []string{project.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
