// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/ccmate/internal/ent/project"
	"github.com/cloverstd/ccmate/internal/ent/projectlabelrule"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplate"
)

// ProjectLabelRule is the model entity for the ProjectLabelRule schema.
type ProjectLabelRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IssueLabel holds the value of the "issue_label" field.
	IssueLabel string `json:"issue_label,omitempty"`
	// TriggerMode holds the value of the "trigger_mode" field.
	TriggerMode projectlabelrule.TriggerMode `json:"trigger_mode,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectLabelRuleQuery when eager-loading is set.
	Edges                       ProjectLabelRuleEdges `json:"edges"`
	project_label_rules         *int
	prompt_template_label_rules *int
	selectValues                sql.SelectValues
}

// ProjectLabelRuleEdges holds the relations/edges for other nodes in the graph.
type ProjectLabelRuleEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// PromptTemplate holds the value of the prompt_template edge.
	PromptTemplate *PromptTemplate `json:"prompt_template,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectLabelRuleEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// PromptTemplateOrErr returns the PromptTemplate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectLabelRuleEdges) PromptTemplateOrErr() (*PromptTemplate, error) {
	if e.PromptTemplate != nil {
		return e.PromptTemplate, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: prompttemplate.Label}
	}
	return nil, &NotLoadedError{edge: "prompt_template"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectLabelRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectlabelrule.FieldID:
			values[i] = new(sql.NullInt64)
		case projectlabelrule.FieldIssueLabel, projectlabelrule.FieldTriggerMode:
			values[i] = new(sql.NullString)
		case projectlabelrule.ForeignKeys[0]: // project_label_rules
			values[i] = new(sql.NullInt64)
		case projectlabelrule.ForeignKeys[1]: // prompt_template_label_rules
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectLabelRule fields.
func (_m *ProjectLabelRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectlabelrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case projectlabelrule.FieldIssueLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issue_label", values[i])
			} else if value.Valid {
				_m.IssueLabel = value.String
			}
		case projectlabelrule.FieldTriggerMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_mode", values[i])
			} else if value.Valid {
				_m.TriggerMode = projectlabelrule.TriggerMode(value.String)
			}
		case projectlabelrule.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_label_rules", value)
			} else if value.Valid {
				_m.project_label_rules = new(int)
				*_m.project_label_rules = int(value.Int64)
			}
		case projectlabelrule.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field prompt_template_label_rules", value)
			} else if value.Valid {
				_m.prompt_template_label_rules = new(int)
				*_m.prompt_template_label_rules = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectLabelRule.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectLabelRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectLabelRule entity.
func (_m *ProjectLabelRule) QueryProject() *ProjectQuery {
	return NewProjectLabelRuleClient(_m.config).QueryProject(_m)
}

// QueryPromptTemplate queries the "prompt_template" edge of the ProjectLabelRule entity.
func (_m *ProjectLabelRule) QueryPromptTemplate() *PromptTemplateQuery {
	return NewProjectLabelRuleClient(_m.config).QueryPromptTemplate(_m)
}

// Update returns a builder for updating this ProjectLabelRule.
// Note that you need to call ProjectLabelRule.Unwrap() before calling this method if this ProjectLabelRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectLabelRule) Update() *ProjectLabelRuleUpdateOne {
	return NewProjectLabelRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectLabelRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectLabelRule) Unwrap() *ProjectLabelRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectLabelRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectLabelRule) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectLabelRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("issue_label=")
	builder.WriteString(_m.IssueLabel)
	builder.WriteString(", ")
	builder.WriteString("trigger_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerMode))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectLabelRules is a parsable slice of ProjectLabelRule.
type ProjectLabelRules []*ProjectLabelRule
