// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplatesnapshot"
	"github.com/cloverstd/ccmate/internal/ent/task"
)

// PromptTemplateSnapshotCreate is the builder for creating a PromptTemplateSnapshot entity.
type PromptTemplateSnapshotCreate struct {
	config
	mutation *PromptTemplateSnapshotMutation
	hooks    []Hook
}

// SetSystemPrompt sets the "system_prompt" field.
func (_c *PromptTemplateSnapshotCreate) SetSystemPrompt(v string) *PromptTemplateSnapshotCreate {
	_c.mutation.SetSystemPrompt(v)
	return _c
}

// SetTaskPrompt sets the "task_prompt" field.
func (_c *PromptTemplateSnapshotCreate) SetTaskPrompt(v string) *PromptTemplateSnapshotCreate {
	_c.mutation.SetTaskPrompt(v)
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *PromptTemplateSnapshotCreate) SetModelName(v string) *PromptTemplateSnapshotCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetModelVersion sets the "model_version" field.
func (_c *PromptTemplateSnapshotCreate) SetModelVersion(v string) *PromptTemplateSnapshotCreate {
	_c.mutation.SetModelVersion(v)
	return _c
}

// SetNillableModelVersion sets the "model_version" field if the given value is not nil.
func (_c *PromptTemplateSnapshotCreate) SetNillableModelVersion(v *string) *PromptTemplateSnapshotCreate {
	if v != nil {
		_c.SetModelVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptTemplateSnapshotCreate) SetCreatedAt(v time.Time) *PromptTemplateSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptTemplateSnapshotCreate) SetNillableCreatedAt(v *time.Time) *PromptTemplateSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTaskID sets the "task" edge to the Task entity by ID.
func (_c *PromptTemplateSnapshotCreate) SetTaskID(id int) *PromptTemplateSnapshotCreate {
	_c.mutation.SetTaskID(id)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *PromptTemplateSnapshotCreate) SetTask(v *Task) *PromptTemplateSnapshotCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the PromptTemplateSnapshotMutation object of the builder.
func (_c *PromptTemplateSnapshotCreate) Mutation() *PromptTemplateSnapshotMutation {
	return _c.mutation
}

// Save creates the PromptTemplateSnapshot in the database.
func (_c *PromptTemplateSnapshotCreate) Save(ctx context.Context) (*PromptTemplateSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptTemplateSnapshotCreate) SaveX(ctx context.Context) *PromptTemplateSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptTemplateSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptTemplateSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptTemplateSnapshotCreate) defaults() {
	if _, ok := _c.mutation.ModelVersion(); !ok {
		v := prompttemplatesnapshot.DefaultModelVersion
		_c.mutation.SetModelVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := prompttemplatesnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptTemplateSnapshotCreate) check() error {
	if _, ok := _c.mutation.SystemPrompt(); !ok {
		return &ValidationError{Name: "system_prompt", err: errors.New(`ent: missing required field "PromptTemplateSnapshot.system_prompt"`)}
	}
	if _, ok := _c.mutation.TaskPrompt(); !ok {
		return &ValidationError{Name: "task_prompt", err: errors.New(`ent: missing required field "PromptTemplateSnapshot.task_prompt"`)}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "PromptTemplateSnapshot.model_name"`)}
	}
	if _, ok := _c.mutation.ModelVersion(); !ok {
		return &ValidationError{Name: "model_version", err: errors.New(`ent: missing required field "PromptTemplateSnapshot.model_version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromptTemplateSnapshot.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "PromptTemplateSnapshot.task"`)}
	}
	return nil
}

func (_c *PromptTemplateSnapshotCreate) sqlSave(ctx context.Context) (*PromptTemplateSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptTemplateSnapshotCreate) createSpec() (*PromptTemplateSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &PromptTemplateSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(prompttemplatesnapshot.Table, sqlgraph.NewFieldSpec(prompttemplatesnapshot.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SystemPrompt(); ok {
		_spec.SetField(prompttemplatesnapshot.FieldSystemPrompt, field.TypeString, value)
		_node.SystemPrompt = value
	}
	if value, ok := _c.mutation.TaskPrompt(); ok {
		_spec.SetField(prompttemplatesnapshot.FieldTaskPrompt, field.TypeString, value)
		_node.TaskPrompt = value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(prompttemplatesnapshot.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.ModelVersion(); ok {
		_spec.SetField(prompttemplatesnapshot.FieldModelVersion, field.TypeString, value)
		_node.ModelVersion = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(prompttemplatesnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   prompttemplatesnapshot.TaskTable,
			Columns: []string{prompttemplatesnapshot.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.task_prompt_snapshot = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PromptTemplateSnapshotCreateBulk is the builder for creating many PromptTemplateSnapshot entities in bulk.
type PromptTemplateSnapshotCreateBulk struct {
	config
	err      error
	builders []*PromptTemplateSnapshotCreate
}

// Save creates the PromptTemplateSnapshot entities in the database.
func (_c *PromptTemplateSnapshotCreateBulk) Save(ctx context.Context) ([]*PromptTemplateSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromptTemplateSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptTemplateSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptTemplateSnapshotCreateBulk) SaveX(ctx context.Context) []*PromptTemplateSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptTemplateSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptTemplateSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
