// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
	"github.com/cloverstd/ccmate/internal/ent/projectlabelrule"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplate"
)

// PromptTemplateUpdate is the builder for updating PromptTemplate entities.
type PromptTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *PromptTemplateMutation
}

// Where appends a list predicates to the PromptTemplateUpdate builder.
func (_u *PromptTemplateUpdate) Where(ps ...predicate.PromptTemplate) *PromptTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PromptTemplateUpdate) SetName(v string) *PromptTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PromptTemplateUpdate) SetNillableName(v *string) *PromptTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *PromptTemplateUpdate) SetSystemPrompt(v string) *PromptTemplateUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *PromptTemplateUpdate) SetNillableSystemPrompt(v *string) *PromptTemplateUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// SetTaskPrompt sets the "task_prompt" field.
func (_u *PromptTemplateUpdate) SetTaskPrompt(v string) *PromptTemplateUpdate {
	_u.mutation.SetTaskPrompt(v)
	return _u
}

// SetNillableTaskPrompt sets the "task_prompt" field if the given value is not nil.
func (_u *PromptTemplateUpdate) SetNillableTaskPrompt(v *string) *PromptTemplateUpdate {
	if v != nil {
		_u.SetTaskPrompt(*v)
	}
	return _u
}

// SetIsBuiltin sets the "is_builtin" field.
func (_u *PromptTemplateUpdate) SetIsBuiltin(v bool) *PromptTemplateUpdate {
	_u.mutation.SetIsBuiltin(v)
	return _u
}

// SetNillableIsBuiltin sets the "is_builtin" field if the given value is not nil.
func (_u *PromptTemplateUpdate) SetNillableIsBuiltin(v *bool) *PromptTemplateUpdate {
	if v != nil {
		_u.SetIsBuiltin(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *PromptTemplateUpdate) SetProjectID(v int) *PromptTemplateUpdate {
	_u.mutation.ResetProjectID()
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *PromptTemplateUpdate) SetNillableProjectID(v *int) *PromptTemplateUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// AddProjectID adds value to the "project_id" field.
func (_u *PromptTemplateUpdate) AddProjectID(v int) *PromptTemplateUpdate {
	_u.mutation.AddProjectID(v)
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *PromptTemplateUpdate) ClearProjectID() *PromptTemplateUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptTemplateUpdate) SetUpdatedAt(v time.Time) *PromptTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLabelRuleIDs adds the "label_rules" edge to the ProjectLabelRule entity by IDs.
func (_u *PromptTemplateUpdate) AddLabelRuleIDs(ids ...int) *PromptTemplateUpdate {
	_u.mutation.AddLabelRuleIDs(ids...)
	return _u
}

// AddLabelRules adds the "label_rules" edges to the ProjectLabelRule entity.
func (_u *PromptTemplateUpdate) AddLabelRules(v ...*ProjectLabelRule) *PromptTemplateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelRuleIDs(ids...)
}

// Mutation returns the PromptTemplateMutation object of the builder.
func (_u *PromptTemplateUpdate) Mutation() *PromptTemplateMutation {
	return _u.mutation
}

// ClearLabelRules clears all "label_rules" edges to the ProjectLabelRule entity.
func (_u *PromptTemplateUpdate) ClearLabelRules() *PromptTemplateUpdate {
	_u.mutation.ClearLabelRules()
	return _u
}

// RemoveLabelRuleIDs removes the "label_rules" edge to ProjectLabelRule entities by IDs.
func (_u *PromptTemplateUpdate) RemoveLabelRuleIDs(ids ...int) *PromptTemplateUpdate {
	_u.mutation.RemoveLabelRuleIDs(ids...)
	return _u
}

// RemoveLabelRules removes "label_rules" edges to ProjectLabelRule entities.
func (_u *PromptTemplateUpdate) RemoveLabelRules(v ...*ProjectLabelRule) *PromptTemplateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelRuleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromptTemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromptTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptTemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prompttemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptTemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := prompttemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromptTemplate.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(prompttemplate.Table, prompttemplate.Columns, sqlgraph.NewFieldSpec(prompttemplate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(prompttemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(prompttemplate.FieldSystemPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskPrompt(); ok {
		_spec.SetField(prompttemplate.FieldTaskPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsBuiltin(); ok {
		_spec.SetField(prompttemplate.FieldIsBuiltin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(prompttemplate.FieldProjectID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProjectID(); ok {
		_spec.AddField(prompttemplate.FieldProjectID, field.TypeInt, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(prompttemplate.FieldProjectID, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LabelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prompttemplate.LabelRulesTable,
			Columns: []string{prompttemplate.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelRulesIDs(); len(nodes) > 0 && !_u.mutation.LabelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prompttemplate.LabelRulesTable,
			Columns: []string{prompttemplate.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prompttemplate.LabelRulesTable,
			Columns: []string{prompttemplate.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prompttemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromptTemplateUpdateOne is the builder for updating a single PromptTemplate entity.
type PromptTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromptTemplateMutation
}

// SetName sets the "name" field.
func (_u *PromptTemplateUpdateOne) SetName(v string) *PromptTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PromptTemplateUpdateOne) SetNillableName(v *string) *PromptTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *PromptTemplateUpdateOne) SetSystemPrompt(v string) *PromptTemplateUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *PromptTemplateUpdateOne) SetNillableSystemPrompt(v *string) *PromptTemplateUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// SetTaskPrompt sets the "task_prompt" field.
func (_u *PromptTemplateUpdateOne) SetTaskPrompt(v string) *PromptTemplateUpdateOne {
	_u.mutation.SetTaskPrompt(v)
	return _u
}

// SetNillableTaskPrompt sets the "task_prompt" field if the given value is not nil.
func (_u *PromptTemplateUpdateOne) SetNillableTaskPrompt(v *string) *PromptTemplateUpdateOne {
	if v != nil {
		_u.SetTaskPrompt(*v)
	}
	return _u
}

// SetIsBuiltin sets the "is_builtin" field.
func (_u *PromptTemplateUpdateOne) SetIsBuiltin(v bool) *PromptTemplateUpdateOne {
	_u.mutation.SetIsBuiltin(v)
	return _u
}

// SetNillableIsBuiltin sets the "is_builtin" field if the given value is not nil.
func (_u *PromptTemplateUpdateOne) SetNillableIsBuiltin(v *bool) *PromptTemplateUpdateOne {
	if v != nil {
		_u.SetIsBuiltin(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *PromptTemplateUpdateOne) SetProjectID(v int) *PromptTemplateUpdateOne {
	_u.mutation.ResetProjectID()
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *PromptTemplateUpdateOne) SetNillableProjectID(v *int) *PromptTemplateUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// AddProjectID adds value to the "project_id" field.
func (_u *PromptTemplateUpdateOne) AddProjectID(v int) *PromptTemplateUpdateOne {
	_u.mutation.AddProjectID(v)
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *PromptTemplateUpdateOne) ClearProjectID() *PromptTemplateUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptTemplateUpdateOne) SetUpdatedAt(v time.Time) *PromptTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddLabelRuleIDs adds the "label_rules" edge to the ProjectLabelRule entity by IDs.
func (_u *PromptTemplateUpdateOne) AddLabelRuleIDs(ids ...int) *PromptTemplateUpdateOne {
	_u.mutation.AddLabelRuleIDs(ids...)
	return _u
}

// AddLabelRules adds the "label_rules" edges to the ProjectLabelRule entity.
func (_u *PromptTemplateUpdateOne) AddLabelRules(v ...*ProjectLabelRule) *PromptTemplateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelRuleIDs(ids...)
}

// Mutation returns the PromptTemplateMutation object of the builder.
func (_u *PromptTemplateUpdateOne) Mutation() *PromptTemplateMutation {
	return _u.mutation
}

// ClearLabelRules clears all "label_rules" edges to the ProjectLabelRule entity.
func (_u *PromptTemplateUpdateOne) ClearLabelRules() *PromptTemplateUpdateOne {
	_u.mutation.ClearLabelRules()
	return _u
}

// RemoveLabelRuleIDs removes the "label_rules" edge to ProjectLabelRule entities by IDs.
func (_u *PromptTemplateUpdateOne) RemoveLabelRuleIDs(ids ...int) *PromptTemplateUpdateOne {
	_u.mutation.RemoveLabelRuleIDs(ids...)
	return _u
}

// RemoveLabelRules removes "label_rules" edges to ProjectLabelRule entities.
func (_u *PromptTemplateUpdateOne) RemoveLabelRules(v ...*ProjectLabelRule) *PromptTemplateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelRuleIDs(ids...)
}

// Where appends a list predicates to the PromptTemplateUpdate builder.
func (_u *PromptTemplateUpdateOne) Where(ps ...predicate.PromptTemplate) *PromptTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromptTemplateUpdateOne) Select(field string, fields ...string) *PromptTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromptTemplate entity.
func (_u *PromptTemplateUpdateOne) Save(ctx context.Context) (*PromptTemplate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptTemplateUpdateOne) SaveX(ctx context.Context) *PromptTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromptTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptTemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prompttemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := prompttemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromptTemplate.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptTemplateUpdateOne) sqlSave(ctx context.Context) (_node *PromptTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(prompttemplate.Table, prompttemplate.Columns, sqlgraph.NewFieldSpec(prompttemplate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromptTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prompttemplate.FieldID)
		for _, f := range fields {
			if !prompttemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prompttemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(prompttemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(prompttemplate.FieldSystemPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskPrompt(); ok {
		_spec.SetField(prompttemplate.FieldTaskPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsBuiltin(); ok {
		_spec.SetField(prompttemplate.FieldIsBuiltin, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(prompttemplate.FieldProjectID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProjectID(); ok {
		_spec.AddField(prompttemplate.FieldProjectID, field.TypeInt, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(prompttemplate.FieldProjectID, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.LabelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prompttemplate.LabelRulesTable,
			Columns: []string{prompttemplate.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelRulesIDs(); len(nodes) > 0 && !_u.mutation.LabelRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prompttemplate.LabelRulesTable,
			Columns: []string{prompttemplate.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   prompttemplate.LabelRulesTable,
			Columns: []string{prompttemplate.LabelRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectlabelrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PromptTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prompttemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
