// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/cloverstd/ccmate/internal/ent/agentprofile"
	"github.com/cloverstd/ccmate/internal/ent/attachment"
	"github.com/cloverstd/ccmate/internal/ent/commandaudit"
	"github.com/cloverstd/ccmate/internal/ent/executionlease"
	"github.com/cloverstd/ccmate/internal/ent/project"
	"github.com/cloverstd/ccmate/internal/ent/projectlabelrule"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplate"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplatesnapshot"
	"github.com/cloverstd/ccmate/internal/ent/schema"
	"github.com/cloverstd/ccmate/internal/ent/session"
	"github.com/cloverstd/ccmate/internal/ent/sessionevent"
	"github.com/cloverstd/ccmate/internal/ent/sessionmessage"
	"github.com/cloverstd/ccmate/internal/ent/task"
	"github.com/cloverstd/ccmate/internal/ent/webhookreceipt"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentprofileFields := schema.AgentProfile{}.Fields()
	_ = agentprofileFields
	// agentprofileDescProvider is the schema descriptor for provider field.
	agentprofileDescProvider := agentprofileFields[0].Descriptor()
	// agentprofile.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	agentprofile.ProviderValidator = agentprofileDescProvider.Validators[0].(func(string) error)
	// agentprofileDescModel is the schema descriptor for model field.
	agentprofileDescModel := agentprofileFields[1].Descriptor()
	// agentprofile.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	agentprofile.ModelValidator = agentprofileDescModel.Validators[0].(func(string) error)
	// agentprofileDescSupportsImage is the schema descriptor for supports_image field.
	agentprofileDescSupportsImage := agentprofileFields[2].Descriptor()
	// agentprofile.DefaultSupportsImage holds the default value on creation for the supports_image field.
	agentprofile.DefaultSupportsImage = agentprofileDescSupportsImage.Default.(bool)
	// agentprofileDescSupportsResume is the schema descriptor for supports_resume field.
	agentprofileDescSupportsResume := agentprofileFields[3].Descriptor()
	// agentprofile.DefaultSupportsResume holds the default value on creation for the supports_resume field.
	agentprofile.DefaultSupportsResume = agentprofileDescSupportsResume.Default.(bool)
	// agentprofileDescConfigJSON is the schema descriptor for config_json field.
	agentprofileDescConfigJSON := agentprofileFields[4].Descriptor()
	// agentprofile.DefaultConfigJSON holds the default value on creation for the config_json field.
	agentprofile.DefaultConfigJSON = agentprofileDescConfigJSON.Default.(string)
	// agentprofileDescCreatedAt is the schema descriptor for created_at field.
	agentprofileDescCreatedAt := agentprofileFields[5].Descriptor()
	// agentprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentprofile.DefaultCreatedAt = agentprofileDescCreatedAt.Default.(func() time.Time)
	// agentprofileDescUpdatedAt is the schema descriptor for updated_at field.
	agentprofileDescUpdatedAt := agentprofileFields[6].Descriptor()
	// agentprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentprofile.DefaultUpdatedAt = agentprofileDescUpdatedAt.Default.(func() time.Time)
	// agentprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentprofile.UpdateDefaultUpdatedAt = agentprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescFileName is the schema descriptor for file_name field.
	attachmentDescFileName := attachmentFields[0].Descriptor()
	// attachment.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	attachment.FileNameValidator = attachmentDescFileName.Validators[0].(func(string) error)
	// attachmentDescMimeType is the schema descriptor for mime_type field.
	attachmentDescMimeType := attachmentFields[1].Descriptor()
	// attachment.DefaultMimeType holds the default value on creation for the mime_type field.
	attachment.DefaultMimeType = attachmentDescMimeType.Default.(string)
	// attachmentDescSize is the schema descriptor for size field.
	attachmentDescSize := attachmentFields[2].Descriptor()
	// attachment.DefaultSize holds the default value on creation for the size field.
	attachment.DefaultSize = attachmentDescSize.Default.(int64)
	// attachmentDescStoragePath is the schema descriptor for storage_path field.
	attachmentDescStoragePath := attachmentFields[3].Descriptor()
	// attachment.StoragePathValidator is a validator for the "storage_path" field. It is called by the builders before save.
	attachment.StoragePathValidator = attachmentDescStoragePath.Validators[0].(func(string) error)
	// attachmentDescCreatedAt is the schema descriptor for created_at field.
	attachmentDescCreatedAt := attachmentFields[4].Descriptor()
	// attachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	attachment.DefaultCreatedAt = attachmentDescCreatedAt.Default.(func() time.Time)
	commandauditFields := schema.CommandAudit{}.Fields()
	_ = commandauditFields
	// commandauditDescSource is the schema descriptor for source field.
	commandauditDescSource := commandauditFields[0].Descriptor()
	// commandaudit.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	commandaudit.SourceValidator = commandauditDescSource.Validators[0].(func(string) error)
	// commandauditDescActor is the schema descriptor for actor field.
	commandauditDescActor := commandauditFields[1].Descriptor()
	// commandaudit.ActorValidator is a validator for the "actor" field. It is called by the builders before save.
	commandaudit.ActorValidator = commandauditDescActor.Validators[0].(func(string) error)
	// commandauditDescCommand is the schema descriptor for command field.
	commandauditDescCommand := commandauditFields[2].Descriptor()
	// commandaudit.CommandValidator is a validator for the "command" field. It is called by the builders before save.
	commandaudit.CommandValidator = commandauditDescCommand.Validators[0].(func(string) error)
	// commandauditDescReason is the schema descriptor for reason field.
	commandauditDescReason := commandauditFields[4].Descriptor()
	// commandaudit.DefaultReason holds the default value on creation for the reason field.
	commandaudit.DefaultReason = commandauditDescReason.Default.(string)
	// commandauditDescCreatedAt is the schema descriptor for created_at field.
	commandauditDescCreatedAt := commandauditFields[5].Descriptor()
	// commandaudit.DefaultCreatedAt holds the default value on creation for the created_at field.
	commandaudit.DefaultCreatedAt = commandauditDescCreatedAt.Default.(func() time.Time)
	executionleaseFields := schema.ExecutionLease{}.Fields()
	_ = executionleaseFields
	// executionleaseDescRunnerID is the schema descriptor for runner_id field.
	executionleaseDescRunnerID := executionleaseFields[0].Descriptor()
	// executionlease.RunnerIDValidator is a validator for the "runner_id" field. It is called by the builders before save.
	executionlease.RunnerIDValidator = executionleaseDescRunnerID.Validators[0].(func(string) error)
	// executionleaseDescStartedAt is the schema descriptor for started_at field.
	executionleaseDescStartedAt := executionleaseFields[1].Descriptor()
	// executionlease.DefaultStartedAt holds the default value on creation for the started_at field.
	executionlease.DefaultStartedAt = executionleaseDescStartedAt.Default.(func() time.Time)
	// executionleaseDescCreatedAt is the schema descriptor for created_at field.
	executionleaseDescCreatedAt := executionleaseFields[3].Descriptor()
	// executionlease.DefaultCreatedAt holds the default value on creation for the created_at field.
	executionlease.DefaultCreatedAt = executionleaseDescCreatedAt.Default.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescRepoURL is the schema descriptor for repo_url field.
	projectDescRepoURL := projectFields[1].Descriptor()
	// project.RepoURLValidator is a validator for the "repo_url" field. It is called by the builders before save.
	project.RepoURLValidator = projectDescRepoURL.Validators[0].(func(string) error)
	// projectDescGitProvider is the schema descriptor for git_provider field.
	projectDescGitProvider := projectFields[2].Descriptor()
	// project.DefaultGitProvider holds the default value on creation for the git_provider field.
	project.DefaultGitProvider = projectDescGitProvider.Default.(string)
	// projectDescDefaultBranch is the schema descriptor for default_branch field.
	projectDescDefaultBranch := projectFields[3].Descriptor()
	// project.DefaultDefaultBranch holds the default value on creation for the default_branch field.
	project.DefaultDefaultBranch = projectDescDefaultBranch.Default.(string)
	// projectDescAutoMode is the schema descriptor for auto_mode field.
	projectDescAutoMode := projectFields[4].Descriptor()
	// project.DefaultAutoMode holds the default value on creation for the auto_mode field.
	project.DefaultAutoMode = projectDescAutoMode.Default.(bool)
	// projectDescMaxConcurrency is the schema descriptor for max_concurrency field.
	projectDescMaxConcurrency := projectFields[5].Descriptor()
	// project.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	project.DefaultMaxConcurrency = projectDescMaxConcurrency.Default.(int)
	// project.MaxConcurrencyValidator is a validator for the "max_concurrency" field. It is called by the builders before save.
	project.MaxConcurrencyValidator = projectDescMaxConcurrency.Validators[0].(func(int) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[6].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[7].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	projectlabelruleFields := schema.ProjectLabelRule{}.Fields()
	_ = projectlabelruleFields
	// projectlabelruleDescIssueLabel is the schema descriptor for issue_label field.
	projectlabelruleDescIssueLabel := projectlabelruleFields[0].Descriptor()
	// projectlabelrule.IssueLabelValidator is a validator for the "issue_label" field. It is called by the builders before save.
	projectlabelrule.IssueLabelValidator = projectlabelruleDescIssueLabel.Validators[0].(func(string) error)
	prompttemplateFields := schema.PromptTemplate{}.Fields()
	_ = prompttemplateFields
	// prompttemplateDescName is the schema descriptor for name field.
	prompttemplateDescName := prompttemplateFields[0].Descriptor()
	// prompttemplate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	prompttemplate.NameValidator = prompttemplateDescName.Validators[0].(func(string) error)
	// prompttemplateDescSystemPrompt is the schema descriptor for system_prompt field.
	prompttemplateDescSystemPrompt := prompttemplateFields[1].Descriptor()
	// prompttemplate.DefaultSystemPrompt holds the default value on creation for the system_prompt field.
	prompttemplate.DefaultSystemPrompt = prompttemplateDescSystemPrompt.Default.(string)
	// prompttemplateDescTaskPrompt is the schema descriptor for task_prompt field.
	prompttemplateDescTaskPrompt := prompttemplateFields[2].Descriptor()
	// prompttemplate.DefaultTaskPrompt holds the default value on creation for the task_prompt field.
	prompttemplate.DefaultTaskPrompt = prompttemplateDescTaskPrompt.Default.(string)
	// prompttemplateDescIsBuiltin is the schema descriptor for is_builtin field.
	prompttemplateDescIsBuiltin := prompttemplateFields[3].Descriptor()
	// prompttemplate.DefaultIsBuiltin holds the default value on creation for the is_builtin field.
	prompttemplate.DefaultIsBuiltin = prompttemplateDescIsBuiltin.Default.(bool)
	// prompttemplateDescCreatedAt is the schema descriptor for created_at field.
	prompttemplateDescCreatedAt := prompttemplateFields[4].Descriptor()
	// prompttemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	prompttemplate.DefaultCreatedAt = prompttemplateDescCreatedAt.Default.(func() time.Time)
	// prompttemplateDescUpdatedAt is the schema descriptor for updated_at field.
	prompttemplateDescUpdatedAt := prompttemplateFields[5].Descriptor()
	// prompttemplate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	prompttemplate.DefaultUpdatedAt = prompttemplateDescUpdatedAt.Default.(func() time.Time)
	// prompttemplate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	prompttemplate.UpdateDefaultUpdatedAt = prompttemplateDescUpdatedAt.UpdateDefault.(func() time.Time)
	prompttemplatesnapshotFields := schema.PromptTemplateSnapshot{}.Fields()
	_ = prompttemplatesnapshotFields
	// prompttemplatesnapshotDescModelVersion is the schema descriptor for model_version field.
	prompttemplatesnapshotDescModelVersion := prompttemplatesnapshotFields[3].Descriptor()
	// prompttemplatesnapshot.DefaultModelVersion holds the default value on creation for the model_version field.
	prompttemplatesnapshot.DefaultModelVersion = prompttemplatesnapshotDescModelVersion.Default.(string)
	// prompttemplatesnapshotDescCreatedAt is the schema descriptor for created_at field.
	prompttemplatesnapshotDescCreatedAt := prompttemplatesnapshotFields[4].Descriptor()
	// prompttemplatesnapshot.DefaultCreatedAt holds the default value on creation for the created_at field.
	prompttemplatesnapshot.DefaultCreatedAt = prompttemplatesnapshotDescCreatedAt.Default.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescProviderSessionKey is the schema descriptor for provider_session_key field.
	sessionDescProviderSessionKey := sessionFields[0].Descriptor()
	// session.DefaultProviderSessionKey holds the default value on creation for the provider_session_key field.
	session.DefaultProviderSessionKey = sessionDescProviderSessionKey.Default.(string)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[4].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	sessioneventFields := schema.SessionEvent{}.Fields()
	_ = sessioneventFields
	// sessioneventDescEventType is the schema descriptor for event_type field.
	sessioneventDescEventType := sessioneventFields[0].Descriptor()
	// sessionevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	sessionevent.EventTypeValidator = sessioneventDescEventType.Validators[0].(func(string) error)
	// sessioneventDescPayloadJSON is the schema descriptor for payload_json field.
	sessioneventDescPayloadJSON := sessioneventFields[1].Descriptor()
	// sessionevent.DefaultPayloadJSON holds the default value on creation for the payload_json field.
	sessionevent.DefaultPayloadJSON = sessioneventDescPayloadJSON.Default.(string)
	// sessioneventDescSequence is the schema descriptor for sequence field.
	sessioneventDescSequence := sessioneventFields[2].Descriptor()
	// sessionevent.DefaultSequence holds the default value on creation for the sequence field.
	sessionevent.DefaultSequence = sessioneventDescSequence.Default.(int)
	// sessioneventDescCreatedAt is the schema descriptor for created_at field.
	sessioneventDescCreatedAt := sessioneventFields[3].Descriptor()
	// sessionevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	sessionevent.DefaultCreatedAt = sessioneventDescCreatedAt.Default.(func() time.Time)
	sessionmessageFields := schema.SessionMessage{}.Fields()
	_ = sessionmessageFields
	// sessionmessageDescRole is the schema descriptor for role field.
	sessionmessageDescRole := sessionmessageFields[0].Descriptor()
	// sessionmessage.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	sessionmessage.RoleValidator = sessionmessageDescRole.Validators[0].(func(string) error)
	// sessionmessageDescContentType is the schema descriptor for content_type field.
	sessionmessageDescContentType := sessionmessageFields[1].Descriptor()
	// sessionmessage.DefaultContentType holds the default value on creation for the content_type field.
	sessionmessage.DefaultContentType = sessionmessageDescContentType.Default.(string)
	// sessionmessageDescSequence is the schema descriptor for sequence field.
	sessionmessageDescSequence := sessionmessageFields[3].Descriptor()
	// sessionmessage.DefaultSequence holds the default value on creation for the sequence field.
	sessionmessage.DefaultSequence = sessionmessageDescSequence.Default.(int)
	// sessionmessageDescCreatedAt is the schema descriptor for created_at field.
	sessionmessageDescCreatedAt := sessionmessageFields[4].Descriptor()
	// sessionmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	sessionmessage.DefaultCreatedAt = sessionmessageDescCreatedAt.Default.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[4].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(int)
	// taskDescTriggerSource is the schema descriptor for trigger_source field.
	taskDescTriggerSource := taskFields[5].Descriptor()
	// task.DefaultTriggerSource holds the default value on creation for the trigger_source field.
	task.DefaultTriggerSource = taskDescTriggerSource.Default.(string)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[7].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[8].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	webhookreceiptFields := schema.WebhookReceipt{}.Fields()
	_ = webhookreceiptFields
	// webhookreceiptDescProvider is the schema descriptor for provider field.
	webhookreceiptDescProvider := webhookreceiptFields[0].Descriptor()
	// webhookreceipt.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	webhookreceipt.ProviderValidator = webhookreceiptDescProvider.Validators[0].(func(string) error)
	// webhookreceiptDescDeliveryID is the schema descriptor for delivery_id field.
	webhookreceiptDescDeliveryID := webhookreceiptFields[1].Descriptor()
	// webhookreceipt.DeliveryIDValidator is a validator for the "delivery_id" field. It is called by the builders before save.
	webhookreceipt.DeliveryIDValidator = webhookreceiptDescDeliveryID.Validators[0].(func(string) error)
	// webhookreceiptDescEventType is the schema descriptor for event_type field.
	webhookreceiptDescEventType := webhookreceiptFields[2].Descriptor()
	// webhookreceipt.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	webhookreceipt.EventTypeValidator = webhookreceiptDescEventType.Validators[0].(func(string) error)
	// webhookreceiptDescReceivedAt is the schema descriptor for received_at field.
	webhookreceiptDescReceivedAt := webhookreceiptFields[3].Descriptor()
	// webhookreceipt.DefaultReceivedAt holds the default value on creation for the received_at field.
	webhookreceipt.DefaultReceivedAt = webhookreceiptDescReceivedAt.Default.(func() time.Time)
	// webhookreceiptDescAccepted is the schema descriptor for accepted field.
	webhookreceiptDescAccepted := webhookreceiptFields[4].Descriptor()
	// webhookreceipt.DefaultAccepted holds the default value on creation for the accepted field.
	webhookreceipt.DefaultAccepted = webhookreceiptDescAccepted.Default.(bool)
}
