// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/attachment"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
	"github.com/cloverstd/ccmate/internal/ent/session"
	"github.com/cloverstd/ccmate/internal/ent/sessionmessage"
)

// SessionMessageUpdate is the builder for updating SessionMessage entities.
type SessionMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMessageMutation
}

// Where appends a list predicates to the SessionMessageUpdate builder.
func (_u *SessionMessageUpdate) Where(ps ...predicate.SessionMessage) *SessionMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRole sets the "role" field.
func (_u *SessionMessageUpdate) SetRole(v string) *SessionMessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableRole(v *string) *SessionMessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *SessionMessageUpdate) SetContentType(v string) *SessionMessageUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableContentType(v *string) *SessionMessageUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SessionMessageUpdate) SetContent(v string) *SessionMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableContent(v *string) *SessionMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *SessionMessageUpdate) SetSequence(v int) *SessionMessageUpdate {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *SessionMessageUpdate) SetNillableSequence(v *int) *SessionMessageUpdate {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *SessionMessageUpdate) AddSequence(v int) *SessionMessageUpdate {
	_u.mutation.AddSequence(v)
	return _u
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_u *SessionMessageUpdate) SetSessionID(id int) *SessionMessageUpdate {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *SessionMessageUpdate) SetSession(v *Session) *SessionMessageUpdate {
	return _u.SetSessionID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *SessionMessageUpdate) AddAttachmentIDs(ids ...int) *SessionMessageUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *SessionMessageUpdate) AddAttachments(v ...*Attachment) *SessionMessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the SessionMessageMutation object of the builder.
func (_u *SessionMessageUpdate) Mutation() *SessionMessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *SessionMessageUpdate) ClearSession() *SessionMessageUpdate {
	_u.mutation.ClearSession()
	return _u
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *SessionMessageUpdate) ClearAttachments() *SessionMessageUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *SessionMessageUpdate) RemoveAttachmentIDs(ids ...int) *SessionMessageUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *SessionMessageUpdate) RemoveAttachments(v ...*Attachment) *SessionMessageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionMessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := sessionmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SessionMessage.role": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SessionMessage.session"`)
	}
	return nil
}

func (_u *SessionMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionmessage.Table, sessionmessage.Columns, sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(sessionmessage.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(sessionmessage.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(sessionmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(sessionmessage.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(sessionmessage.FieldSequence, field.TypeInt, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionmessage.AttachmentsTable,
			Columns: []string{sessionmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionmessage.AttachmentsTable,
			Columns: []string{sessionmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionmessage.AttachmentsTable,
			Columns: []string{sessionmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionMessageUpdateOne is the builder for updating a single SessionMessage entity.
type SessionMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMessageMutation
}

// SetRole sets the "role" field.
func (_u *SessionMessageUpdateOne) SetRole(v string) *SessionMessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableRole(v *string) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *SessionMessageUpdateOne) SetContentType(v string) *SessionMessageUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableContentType(v *string) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SessionMessageUpdateOne) SetContent(v string) *SessionMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableContent(v *string) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSequence sets the "sequence" field.
func (_u *SessionMessageUpdateOne) SetSequence(v int) *SessionMessageUpdateOne {
	_u.mutation.ResetSequence()
	_u.mutation.SetSequence(v)
	return _u
}

// SetNillableSequence sets the "sequence" field if the given value is not nil.
func (_u *SessionMessageUpdateOne) SetNillableSequence(v *int) *SessionMessageUpdateOne {
	if v != nil {
		_u.SetSequence(*v)
	}
	return _u
}

// AddSequence adds value to the "sequence" field.
func (_u *SessionMessageUpdateOne) AddSequence(v int) *SessionMessageUpdateOne {
	_u.mutation.AddSequence(v)
	return _u
}

// SetSessionID sets the "session" edge to the Session entity by ID.
func (_u *SessionMessageUpdateOne) SetSessionID(id int) *SessionMessageUpdateOne {
	_u.mutation.SetSessionID(id)
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *SessionMessageUpdateOne) SetSession(v *Session) *SessionMessageUpdateOne {
	return _u.SetSessionID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_u *SessionMessageUpdateOne) AddAttachmentIDs(ids ...int) *SessionMessageUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_u *SessionMessageUpdateOne) AddAttachments(v ...*Attachment) *SessionMessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// Mutation returns the SessionMessageMutation object of the builder.
func (_u *SessionMessageUpdateOne) Mutation() *SessionMessageMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *SessionMessageUpdateOne) ClearSession() *SessionMessageUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (_u *SessionMessageUpdateOne) ClearAttachments() *SessionMessageUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (_u *SessionMessageUpdateOne) RemoveAttachmentIDs(ids ...int) *SessionMessageUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (_u *SessionMessageUpdateOne) RemoveAttachments(v ...*Attachment) *SessionMessageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the SessionMessageUpdate builder.
func (_u *SessionMessageUpdateOne) Where(ps ...predicate.SessionMessage) *SessionMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionMessageUpdateOne) Select(field string, fields ...string) *SessionMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SessionMessage entity.
func (_u *SessionMessageUpdateOne) Save(ctx context.Context) (*SessionMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionMessageUpdateOne) SaveX(ctx context.Context) *SessionMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := sessionmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SessionMessage.role": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SessionMessage.session"`)
	}
	return nil
}

func (_u *SessionMessageUpdateOne) sqlSave(ctx context.Context) (_node *SessionMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sessionmessage.Table, sessionmessage.Columns, sqlgraph.NewFieldSpec(sessionmessage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SessionMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sessionmessage.FieldID)
		for _, f := range fields {
			if !sessionmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sessionmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(sessionmessage.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(sessionmessage.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(sessionmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sequence(); ok {
		_spec.SetField(sessionmessage.FieldSequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequence(); ok {
		_spec.AddField(sessionmessage.FieldSequence, field.TypeInt, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sessionmessage.SessionTable,
			Columns: []string{sessionmessage.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionmessage.AttachmentsTable,
			Columns: []string{sessionmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionmessage.AttachmentsTable,
			Columns: []string{sessionmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sessionmessage.AttachmentsTable,
			Columns: []string{sessionmessage.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SessionMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sessionmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
