// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/ccmate/internal/ent/executionlease"
	"github.com/cloverstd/ccmate/internal/ent/project"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplatesnapshot"
	"github.com/cloverstd/ccmate/internal/ent/task"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IssueNumber holds the value of the "issue_number" field.
	IssueNumber int `json:"issue_number,omitempty"`
	// PrNumber holds the value of the "pr_number" field.
	PrNumber *int `json:"pr_number,omitempty"`
	// AgentProfileID holds the value of the "agent_profile_id" field.
	AgentProfileID *int `json:"agent_profile_id,omitempty"`
	// Type holds the value of the "type" field.
	Type task.Type `json:"type,omitempty"`
	// ReviewIteration holds the value of the "review_iteration" field.
	ReviewIteration int `json:"review_iteration,omitempty"`
	// Status holds the value of the "status" field.
	Status task.Status `json:"status,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// TriggerSource holds the value of the "trigger_source" field.
	TriggerSource string `json:"trigger_source,omitempty"`
	// CurrentSessionID holds the value of the "current_session_id" field.
	CurrentSessionID *int `json:"current_session_id,omitempty"`
	// TelegramChatID holds the value of the "telegram_chat_id" field.
	TelegramChatID *string `json:"-"`
	// TelegramMessageID holds the value of the "telegram_message_id" field.
	TelegramMessageID *int64 `json:"telegram_message_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges         TaskEdges `json:"edges"`
	project_tasks *int
	selectValues  sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Sessions holds the value of the sessions edge.
	Sessions []*Session `json:"sessions,omitempty"`
	// PromptSnapshot holds the value of the prompt_snapshot edge.
	PromptSnapshot *PromptTemplateSnapshot `json:"prompt_snapshot,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*Attachment `json:"attachments,omitempty"`
	// CommandAudits holds the value of the command_audits edge.
	CommandAudits []*CommandAudit `json:"command_audits,omitempty"`
	// ExecutionLease holds the value of the execution_lease edge.
	ExecutionLease *ExecutionLease `json:"execution_lease,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) SessionsOrErr() ([]*Session, error) {
	if e.loadedTypes[1] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// PromptSnapshotOrErr returns the PromptSnapshot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) PromptSnapshotOrErr() (*PromptTemplateSnapshot, error) {
	if e.PromptSnapshot != nil {
		return e.PromptSnapshot, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: prompttemplatesnapshot.Label}
	}
	return nil, &NotLoadedError{edge: "prompt_snapshot"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) AttachmentsOrErr() ([]*Attachment, error) {
	if e.loadedTypes[3] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// CommandAuditsOrErr returns the CommandAudits value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) CommandAuditsOrErr() ([]*CommandAudit, error) {
	if e.loadedTypes[4] {
		return e.CommandAudits, nil
	}
	return nil, &NotLoadedError{edge: "command_audits"}
}

// ExecutionLeaseOrErr returns the ExecutionLease value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ExecutionLeaseOrErr() (*ExecutionLease, error) {
	if e.ExecutionLease != nil {
		return e.ExecutionLease, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: executionlease.Label}
	}
	return nil, &NotLoadedError{edge: "execution_lease"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldID, task.FieldIssueNumber, task.FieldPrNumber, task.FieldAgentProfileID, task.FieldReviewIteration, task.FieldPriority, task.FieldCurrentSessionID, task.FieldTelegramMessageID:
			values[i] = new(sql.NullInt64)
		case task.FieldType, task.FieldStatus, task.FieldTriggerSource, task.FieldTelegramChatID:
			values[i] = new(sql.NullString)
		case task.FieldCreatedAt, task.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case task.ForeignKeys[0]: // project_tasks
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case task.FieldIssueNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issue_number", values[i])
			} else if value.Valid {
				_m.IssueNumber = int(value.Int64)
			}
		case task.FieldPrNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pr_number", values[i])
			} else if value.Valid {
				_m.PrNumber = new(int)
				*_m.PrNumber = int(value.Int64)
			}
		case task.FieldAgentProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_profile_id", values[i])
			} else if value.Valid {
				_m.AgentProfileID = new(int)
				*_m.AgentProfileID = int(value.Int64)
			}
		case task.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = task.Type(value.String)
			}
		case task.FieldReviewIteration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field review_iteration", values[i])
			} else if value.Valid {
				_m.ReviewIteration = int(value.Int64)
			}
		case task.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = task.Status(value.String)
			}
		case task.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case task.FieldTriggerSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_source", values[i])
			} else if value.Valid {
				_m.TriggerSource = value.String
			}
		case task.FieldCurrentSessionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_session_id", values[i])
			} else if value.Valid {
				_m.CurrentSessionID = new(int)
				*_m.CurrentSessionID = int(value.Int64)
			}
		case task.FieldTelegramChatID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field telegram_chat_id", values[i])
			} else if value.Valid {
				_m.TelegramChatID = new(string)
				*_m.TelegramChatID = value.String
			}
		case task.FieldTelegramMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field telegram_message_id", values[i])
			} else if value.Valid {
				_m.TelegramMessageID = new(int64)
				*_m.TelegramMessageID = value.Int64
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case task.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case task.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_tasks", value)
			} else if value.Valid {
				_m.project_tasks = new(int)
				*_m.project_tasks = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Task entity.
func (_m *Task) QueryProject() *ProjectQuery {
	return NewTaskClient(_m.config).QueryProject(_m)
}

// QuerySessions queries the "sessions" edge of the Task entity.
func (_m *Task) QuerySessions() *SessionQuery {
	return NewTaskClient(_m.config).QuerySessions(_m)
}

// QueryPromptSnapshot queries the "prompt_snapshot" edge of the Task entity.
func (_m *Task) QueryPromptSnapshot() *PromptTemplateSnapshotQuery {
	return NewTaskClient(_m.config).QueryPromptSnapshot(_m)
}

// QueryAttachments queries the "attachments" edge of the Task entity.
func (_m *Task) QueryAttachments() *AttachmentQuery {
	return NewTaskClient(_m.config).QueryAttachments(_m)
}

// QueryCommandAudits queries the "command_audits" edge of the Task entity.
func (_m *Task) QueryCommandAudits() *CommandAuditQuery {
	return NewTaskClient(_m.config).QueryCommandAudits(_m)
}

// QueryExecutionLease queries the "execution_lease" edge of the Task entity.
func (_m *Task) QueryExecutionLease() *ExecutionLeaseQuery {
	return NewTaskClient(_m.config).QueryExecutionLease(_m)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("issue_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.IssueNumber))
	builder.WriteString(", ")
	if v := _m.PrNumber; v != nil {
		builder.WriteString("pr_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AgentProfileID; v != nil {
		builder.WriteString("agent_profile_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("review_iteration=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewIteration))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("trigger_source=")
	builder.WriteString(_m.TriggerSource)
	builder.WriteString(", ")
	if v := _m.CurrentSessionID; v != nil {
		builder.WriteString("current_session_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("telegram_chat_id=<sensitive>")
	builder.WriteString(", ")
	if v := _m.TelegramMessageID; v != nil {
		builder.WriteString("telegram_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
