// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloverstd/ccmate/internal/ent/attachment"
	"github.com/cloverstd/ccmate/internal/ent/commandaudit"
	"github.com/cloverstd/ccmate/internal/ent/executionlease"
	"github.com/cloverstd/ccmate/internal/ent/project"
	"github.com/cloverstd/ccmate/internal/ent/prompttemplatesnapshot"
	"github.com/cloverstd/ccmate/internal/ent/session"
	"github.com/cloverstd/ccmate/internal/ent/task"
)

// TaskCreate is the builder for creating a Task entity.
type TaskCreate struct {
	config
	mutation *TaskMutation
	hooks    []Hook
}

// SetIssueNumber sets the "issue_number" field.
func (_c *TaskCreate) SetIssueNumber(v int) *TaskCreate {
	_c.mutation.SetIssueNumber(v)
	return _c
}

// SetPrNumber sets the "pr_number" field.
func (_c *TaskCreate) SetPrNumber(v int) *TaskCreate {
	_c.mutation.SetPrNumber(v)
	return _c
}

// SetNillablePrNumber sets the "pr_number" field if the given value is not nil.
func (_c *TaskCreate) SetNillablePrNumber(v *int) *TaskCreate {
	if v != nil {
		_c.SetPrNumber(*v)
	}
	return _c
}

// SetAgentProfileID sets the "agent_profile_id" field.
func (_c *TaskCreate) SetAgentProfileID(v int) *TaskCreate {
	_c.mutation.SetAgentProfileID(v)
	return _c
}

// SetNillableAgentProfileID sets the "agent_profile_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableAgentProfileID(v *int) *TaskCreate {
	if v != nil {
		_c.SetAgentProfileID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *TaskCreate) SetType(v task.Type) *TaskCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TaskCreate) SetStatus(v task.Status) *TaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TaskCreate) SetNillableStatus(v *task.Status) *TaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *TaskCreate) SetPriority(v int) *TaskCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *TaskCreate) SetNillablePriority(v *int) *TaskCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetTriggerSource sets the "trigger_source" field.
func (_c *TaskCreate) SetTriggerSource(v string) *TaskCreate {
	_c.mutation.SetTriggerSource(v)
	return _c
}

// SetNillableTriggerSource sets the "trigger_source" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTriggerSource(v *string) *TaskCreate {
	if v != nil {
		_c.SetTriggerSource(*v)
	}
	return _c
}

// SetCurrentSessionID sets the "current_session_id" field.
func (_c *TaskCreate) SetCurrentSessionID(v int) *TaskCreate {
	_c.mutation.SetCurrentSessionID(v)
	return _c
}

// SetNillableCurrentSessionID sets the "current_session_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCurrentSessionID(v *int) *TaskCreate {
	if v != nil {
		_c.SetCurrentSessionID(*v)
	}
	return _c
}

// SetTelegramChatID sets the "telegram_chat_id" field.
func (_c *TaskCreate) SetTelegramChatID(v string) *TaskCreate {
	_c.mutation.SetTelegramChatID(v)
	return _c
}

// SetNillableTelegramChatID sets the "telegram_chat_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTelegramChatID(v *string) *TaskCreate {
	if v != nil {
		_c.SetTelegramChatID(*v)
	}
	return _c
}

// SetTelegramMessageID sets the "telegram_message_id" field.
func (_c *TaskCreate) SetTelegramMessageID(v int64) *TaskCreate {
	_c.mutation.SetTelegramMessageID(v)
	return _c
}

// SetNillableTelegramMessageID sets the "telegram_message_id" field if the given value is not nil.
func (_c *TaskCreate) SetNillableTelegramMessageID(v *int64) *TaskCreate {
	if v != nil {
		_c.SetTelegramMessageID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TaskCreate) SetCreatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableCreatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TaskCreate) SetUpdatedAt(v time.Time) *TaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TaskCreate) SetNillableUpdatedAt(v *time.Time) *TaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *TaskCreate) SetProjectID(id int) *TaskCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *TaskCreate) SetProject(v *Project) *TaskCreate {
	return _c.SetProjectID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (_c *TaskCreate) AddSessionIDs(ids ...int) *TaskCreate {
	_c.mutation.AddSessionIDs(ids...)
	return _c
}

// AddSessions adds the "sessions" edges to the Session entity.
func (_c *TaskCreate) AddSessions(v ...*Session) *TaskCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSessionIDs(ids...)
}

// SetPromptSnapshotID sets the "prompt_snapshot" edge to the PromptTemplateSnapshot entity by ID.
func (_c *TaskCreate) SetPromptSnapshotID(id int) *TaskCreate {
	_c.mutation.SetPromptSnapshotID(id)
	return _c
}

// SetNillablePromptSnapshotID sets the "prompt_snapshot" edge to the PromptTemplateSnapshot entity by ID if the given value is not nil.
func (_c *TaskCreate) SetNillablePromptSnapshotID(id *int) *TaskCreate {
	if id != nil {
		_c = _c.SetPromptSnapshotID(*id)
	}
	return _c
}

// SetPromptSnapshot sets the "prompt_snapshot" edge to the PromptTemplateSnapshot entity.
func (_c *TaskCreate) SetPromptSnapshot(v *PromptTemplateSnapshot) *TaskCreate {
	return _c.SetPromptSnapshotID(v.ID)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_c *TaskCreate) AddAttachmentIDs(ids ...int) *TaskCreate {
	_c.mutation.AddAttachmentIDs(ids...)
	return _c
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_c *TaskCreate) AddAttachments(v ...*Attachment) *TaskCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttachmentIDs(ids...)
}

// AddCommandAuditIDs adds the "command_audits" edge to the CommandAudit entity by IDs.
func (_c *TaskCreate) AddCommandAuditIDs(ids ...int) *TaskCreate {
	_c.mutation.AddCommandAuditIDs(ids...)
	return _c
}

// AddCommandAudits adds the "command_audits" edges to the CommandAudit entity.
func (_c *TaskCreate) AddCommandAudits(v ...*CommandAudit) *TaskCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommandAuditIDs(ids...)
}

// SetExecutionLeaseID sets the "execution_lease" edge to the ExecutionLease entity by ID.
func (_c *TaskCreate) SetExecutionLeaseID(id int) *TaskCreate {
	_c.mutation.SetExecutionLeaseID(id)
	return _c
}

// SetNillableExecutionLeaseID sets the "execution_lease" edge to the ExecutionLease entity by ID if the given value is not nil.
func (_c *TaskCreate) SetNillableExecutionLeaseID(id *int) *TaskCreate {
	if id != nil {
		_c = _c.SetExecutionLeaseID(*id)
	}
	return _c
}

// SetExecutionLease sets the "execution_lease" edge to the ExecutionLease entity.
func (_c *TaskCreate) SetExecutionLease(v *ExecutionLease) *TaskCreate {
	return _c.SetExecutionLeaseID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_c *TaskCreate) Mutation() *TaskMutation {
	return _c.mutation
}

// Save creates the Task in the database.
func (_c *TaskCreate) Save(ctx context.Context) (*Task, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCreate) SaveX(ctx context.Context) *Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := task.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := task.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.TriggerSource(); !ok {
		v := task.DefaultTriggerSource
		_c.mutation.SetTriggerSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := task.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := task.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCreate) check() error {
	if _, ok := _c.mutation.IssueNumber(); !ok {
		return &ValidationError{Name: "issue_number", err: errors.New(`ent: missing required field "Task.issue_number"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Task.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := task.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Task.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Task.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Task.priority"`)}
	}
	if _, ok := _c.mutation.TriggerSource(); !ok {
		return &ValidationError{Name: "trigger_source", err: errors.New(`ent: missing required field "Task.trigger_source"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Task.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Task.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Task.project"`)}
	}
	return nil
}

func (_c *TaskCreate) sqlSave(ctx context.Context) (*Task, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCreate) createSpec() (*Task, *sqlgraph.CreateSpec) {
	var (
		_node = &Task{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(task.Table, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.IssueNumber(); ok {
		_spec.SetField(task.FieldIssueNumber, field.TypeInt, value)
		_node.IssueNumber = value
	}
	if value, ok := _c.mutation.PrNumber(); ok {
		_spec.SetField(task.FieldPrNumber, field.TypeInt, value)
		_node.PrNumber = &value
	}
	if value, ok := _c.mutation.AgentProfileID(); ok {
		_spec.SetField(task.FieldAgentProfileID, field.TypeInt, value)
		_node.AgentProfileID = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(task.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.TriggerSource(); ok {
		_spec.SetField(task.FieldTriggerSource, field.TypeString, value)
		_node.TriggerSource = value
	}
	if value, ok := _c.mutation.CurrentSessionID(); ok {
		_spec.SetField(task.FieldCurrentSessionID, field.TypeInt, value)
		_node.CurrentSessionID = &value
	}
	if value, ok := _c.mutation.TelegramChatID(); ok {
		_spec.SetField(task.FieldTelegramChatID, field.TypeString, value)
		_node.TelegramChatID = &value
	}
	if value, ok := _c.mutation.TelegramMessageID(); ok {
		_spec.SetField(task.FieldTelegramMessageID, field.TypeInt64, value)
		_node.TelegramMessageID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(task.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_tasks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.SessionsTable,
			Columns: []string{task.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PromptSnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.PromptSnapshotTable,
			Columns: []string{task.PromptSnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(prompttemplatesnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommandAuditsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommandAuditsTable,
			Columns: []string{task.CommandAuditsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commandaudit.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExecutionLeaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   task.ExecutionLeaseTable,
			Columns: []string{task.ExecutionLeaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(executionlease.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCreateBulk is the builder for creating many Task entities in bulk.
type TaskCreateBulk struct {
	config
	err      error
	builders []*TaskCreate
}

// Save creates the Task entities in the database.
func (_c *TaskCreateBulk) Save(ctx context.Context) ([]*Task, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Task, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCreateBulk) SaveX(ctx context.Context) []*Task {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
