// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/ccmate/internal/ent/webhookreceipt"
)

// WebhookReceipt is the model entity for the WebhookReceipt schema.
type WebhookReceipt struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// DeliveryID holds the value of the "delivery_id" field.
	DeliveryID string `json:"delivery_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// Accepted holds the value of the "accepted" field.
	Accepted     bool `json:"accepted,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebhookReceipt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webhookreceipt.FieldAccepted:
			values[i] = new(sql.NullBool)
		case webhookreceipt.FieldID:
			values[i] = new(sql.NullInt64)
		case webhookreceipt.FieldProvider, webhookreceipt.FieldDeliveryID, webhookreceipt.FieldEventType:
			values[i] = new(sql.NullString)
		case webhookreceipt.FieldReceivedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebhookReceipt fields.
func (_m *WebhookReceipt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webhookreceipt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case webhookreceipt.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case webhookreceipt.FieldDeliveryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_id", values[i])
			} else if value.Valid {
				_m.DeliveryID = value.String
			}
		case webhookreceipt.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case webhookreceipt.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		case webhookreceipt.FieldAccepted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field accepted", values[i])
			} else if value.Valid {
				_m.Accepted = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebhookReceipt.
// This includes values selected through modifiers, order, etc.
func (_m *WebhookReceipt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this WebhookReceipt.
// Note that you need to call WebhookReceipt.Unwrap() before calling this method if this WebhookReceipt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WebhookReceipt) Update() *WebhookReceiptUpdateOne {
	return NewWebhookReceiptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WebhookReceipt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WebhookReceipt) Unwrap() *WebhookReceipt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WebhookReceipt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WebhookReceipt) String() string {
	var builder strings.Builder
	builder.WriteString("WebhookReceipt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("delivery_id=")
	builder.WriteString(_m.DeliveryID)
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("accepted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Accepted))
	builder.WriteByte(')')
	return builder.String()
}

// WebhookReceipts is a parsable slice of WebhookReceipt.
type WebhookReceipts []*WebhookReceipt
