// Code generated by ent, DO NOT EDIT.

package projectlabelrule

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the projectlabelrule type in the database.
	Label = "project_label_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIssueLabel holds the string denoting the issue_label field in the database.
	FieldIssueLabel = "issue_label"
	// FieldTriggerMode holds the string denoting the trigger_mode field in the database.
	FieldTriggerMode = "trigger_mode"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgePromptTemplate holds the string denoting the prompt_template edge name in mutations.
	EdgePromptTemplate = "prompt_template"
	// Table holds the table name of the projectlabelrule in the database.
	Table = "project_label_rules"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "project_label_rules"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_label_rules"
	// PromptTemplateTable is the table that holds the prompt_template relation/edge.
	PromptTemplateTable = "project_label_rules"
	// PromptTemplateInverseTable is the table name for the PromptTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "prompttemplate" package.
	PromptTemplateInverseTable = "prompt_templates"
	// PromptTemplateColumn is the table column denoting the prompt_template relation/edge.
	PromptTemplateColumn = "prompt_template_label_rules"
)

// Columns holds all SQL columns for projectlabelrule fields.
var Columns = []string{
	FieldID,
	FieldIssueLabel,
	FieldTriggerMode,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "project_label_rules"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"project_label_rules",
	"prompt_template_label_rules",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// IssueLabelValidator is a validator for the "issue_label" field. It is called by the builders before save.
	IssueLabelValidator func(string) error
)

// TriggerMode defines the type for the "trigger_mode" enum field.
type TriggerMode string

// TriggerModeAuto is the default value of the TriggerMode enum.
const DefaultTriggerMode = TriggerModeAuto

// TriggerMode values.
const (
	TriggerModeAuto   TriggerMode = "auto"
	TriggerModeManual TriggerMode = "manual"
)

func (tm TriggerMode) String() string {
	return string(tm)
}

// TriggerModeValidator is a validator for the "trigger_mode" field enum values. It is called by the builders before save.
func TriggerModeValidator(tm TriggerMode) error {
	switch tm {
	case TriggerModeAuto, TriggerModeManual:
		return nil
	default:
		return fmt.Errorf("projectlabelrule: invalid enum value for trigger_mode field: %q", tm)
	}
}

// OrderOption defines the ordering options for the ProjectLabelRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIssueLabel orders the results by the issue_label field.
func ByIssueLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssueLabel, opts...).ToFunc()
}

// ByTriggerMode orders the results by the trigger_mode field.
func ByTriggerMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerMode, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByPromptTemplateField orders the results by prompt_template field.
func ByPromptTemplateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPromptTemplateStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newPromptTemplateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PromptTemplateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PromptTemplateTable, PromptTemplateColumn),
	)
}
