// Code generated by ent, DO NOT EDIT.

package task

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIssueNumber holds the string denoting the issue_number field in the database.
	FieldIssueNumber = "issue_number"
	// FieldPrNumber holds the string denoting the pr_number field in the database.
	FieldPrNumber = "pr_number"
	// FieldAgentProfileID holds the string denoting the agent_profile_id field in the database.
	FieldAgentProfileID = "agent_profile_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldTriggerSource holds the string denoting the trigger_source field in the database.
	FieldTriggerSource = "trigger_source"
	// FieldCurrentSessionID holds the string denoting the current_session_id field in the database.
	FieldCurrentSessionID = "current_session_id"
	// FieldTelegramChatID holds the string denoting the telegram_chat_id field in the database.
	FieldTelegramChatID = "telegram_chat_id"
	// FieldTelegramMessageID holds the string denoting the telegram_message_id field in the database.
	FieldTelegramMessageID = "telegram_message_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgePromptSnapshot holds the string denoting the prompt_snapshot edge name in mutations.
	EdgePromptSnapshot = "prompt_snapshot"
	// EdgeAttachments holds the string denoting the attachments edge name in mutations.
	EdgeAttachments = "attachments"
	// EdgeCommandAudits holds the string denoting the command_audits edge name in mutations.
	EdgeCommandAudits = "command_audits"
	// EdgeExecutionLease holds the string denoting the execution_lease edge name in mutations.
	EdgeExecutionLease = "execution_lease"
	// Table holds the table name of the task in the database.
	Table = "tasks"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "tasks"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_tasks"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "task_sessions"
	// PromptSnapshotTable is the table that holds the prompt_snapshot relation/edge.
	PromptSnapshotTable = "prompt_template_snapshots"
	// PromptSnapshotInverseTable is the table name for the PromptTemplateSnapshot entity.
	// It exists in this package in order to avoid circular dependency with the "prompttemplatesnapshot" package.
	PromptSnapshotInverseTable = "prompt_template_snapshots"
	// PromptSnapshotColumn is the table column denoting the prompt_snapshot relation/edge.
	PromptSnapshotColumn = "task_prompt_snapshot"
	// AttachmentsTable is the table that holds the attachments relation/edge.
	AttachmentsTable = "attachments"
	// AttachmentsInverseTable is the table name for the Attachment entity.
	// It exists in this package in order to avoid circular dependency with the "attachment" package.
	AttachmentsInverseTable = "attachments"
	// AttachmentsColumn is the table column denoting the attachments relation/edge.
	AttachmentsColumn = "task_attachments"
	// CommandAuditsTable is the table that holds the command_audits relation/edge.
	CommandAuditsTable = "command_audits"
	// CommandAuditsInverseTable is the table name for the CommandAudit entity.
	// It exists in this package in order to avoid circular dependency with the "commandaudit" package.
	CommandAuditsInverseTable = "command_audits"
	// CommandAuditsColumn is the table column denoting the command_audits relation/edge.
	CommandAuditsColumn = "task_command_audits"
	// ExecutionLeaseTable is the table that holds the execution_lease relation/edge.
	ExecutionLeaseTable = "execution_leases"
	// ExecutionLeaseInverseTable is the table name for the ExecutionLease entity.
	// It exists in this package in order to avoid circular dependency with the "executionlease" package.
	ExecutionLeaseInverseTable = "execution_leases"
	// ExecutionLeaseColumn is the table column denoting the execution_lease relation/edge.
	ExecutionLeaseColumn = "task_execution_lease"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldIssueNumber,
	FieldPrNumber,
	FieldAgentProfileID,
	FieldType,
	FieldStatus,
	FieldPriority,
	FieldTriggerSource,
	FieldCurrentSessionID,
	FieldTelegramChatID,
	FieldTelegramMessageID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tasks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"project_tasks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultTriggerSource holds the default value on creation for the "trigger_source" field.
	DefaultTriggerSource string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeIssueImplementation Type = "issue_implementation"
	TypeReviewFix           Type = "review_fix"
	TypeManualFollowup      Type = "manual_followup"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeIssueImplementation, TypeReviewFix, TypeManualFollowup:
		return nil
	default:
		return fmt.Errorf("task: invalid enum value for type field: %q", _type)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusQueued is the default value of the Status enum.
const DefaultStatus = StatusQueued

// Status values.
const (
	StatusPending     Status = "pending"
	StatusQueued      Status = "queued"
	StatusRunning     Status = "running"
	StatusPaused      Status = "paused"
	StatusWaitingUser Status = "waiting_user"
	StatusSucceeded   Status = "succeeded"
	StatusFailed      Status = "failed"
	StatusCancelled   Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusQueued, StatusRunning, StatusPaused, StatusWaitingUser, StatusSucceeded, StatusFailed, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("task: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Task queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIssueNumber orders the results by the issue_number field.
func ByIssueNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssueNumber, opts...).ToFunc()
}

// ByPrNumber orders the results by the pr_number field.
func ByPrNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrNumber, opts...).ToFunc()
}

// ByAgentProfileID orders the results by the agent_profile_id field.
func ByAgentProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentProfileID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByTriggerSource orders the results by the trigger_source field.
func ByTriggerSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerSource, opts...).ToFunc()
}

// ByCurrentSessionID orders the results by the current_session_id field.
func ByCurrentSessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentSessionID, opts...).ToFunc()
}

// ByTelegramChatID orders the results by the telegram_chat_id field.
func ByTelegramChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelegramChatID, opts...).ToFunc()
}

// ByTelegramMessageID orders the results by the telegram_message_id field.
func ByTelegramMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTelegramMessageID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPromptSnapshotField orders the results by prompt_snapshot field.
func ByPromptSnapshotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPromptSnapshotStep(), sql.OrderByField(field, opts...))
	}
}

// ByAttachmentsCount orders the results by attachments count.
func ByAttachmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttachmentsStep(), opts...)
	}
}

// ByAttachments orders the results by attachments terms.
func ByAttachments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttachmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommandAuditsCount orders the results by command_audits count.
func ByCommandAuditsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommandAuditsStep(), opts...)
	}
}

// ByCommandAudits orders the results by command_audits terms.
func ByCommandAudits(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommandAuditsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExecutionLeaseField orders the results by execution_lease field.
func ByExecutionLeaseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExecutionLeaseStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newPromptSnapshotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PromptSnapshotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, PromptSnapshotTable, PromptSnapshotColumn),
	)
}
func newAttachmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttachmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
	)
}
func newCommandAuditsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommandAuditsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommandAuditsTable, CommandAuditsColumn),
	)
}
func newExecutionLeaseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExecutionLeaseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, ExecutionLeaseTable, ExecutionLeaseColumn),
	)
}
