// Code generated by ent, DO NOT EDIT.

package task

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldID, id))
}

// IssueNumber applies equality check predicate on the "issue_number" field. It's identical to IssueNumberEQ.
func IssueNumber(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldIssueNumber, v))
}

// PrNumber applies equality check predicate on the "pr_number" field. It's identical to PrNumberEQ.
func PrNumber(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPrNumber, v))
}

// AgentProfileID applies equality check predicate on the "agent_profile_id" field. It's identical to AgentProfileIDEQ.
func AgentProfileID(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAgentProfileID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPriority, v))
}

// TriggerSource applies equality check predicate on the "trigger_source" field. It's identical to TriggerSourceEQ.
func TriggerSource(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTriggerSource, v))
}

// CurrentSessionID applies equality check predicate on the "current_session_id" field. It's identical to CurrentSessionIDEQ.
func CurrentSessionID(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCurrentSessionID, v))
}

// TelegramChatID applies equality check predicate on the "telegram_chat_id" field. It's identical to TelegramChatIDEQ.
func TelegramChatID(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTelegramChatID, v))
}

// TelegramMessageID applies equality check predicate on the "telegram_message_id" field. It's identical to TelegramMessageIDEQ.
func TelegramMessageID(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTelegramMessageID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// IssueNumberEQ applies the EQ predicate on the "issue_number" field.
func IssueNumberEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldIssueNumber, v))
}

// IssueNumberNEQ applies the NEQ predicate on the "issue_number" field.
func IssueNumberNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldIssueNumber, v))
}

// IssueNumberIn applies the In predicate on the "issue_number" field.
func IssueNumberIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldIssueNumber, vs...))
}

// IssueNumberNotIn applies the NotIn predicate on the "issue_number" field.
func IssueNumberNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldIssueNumber, vs...))
}

// IssueNumberGT applies the GT predicate on the "issue_number" field.
func IssueNumberGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldIssueNumber, v))
}

// IssueNumberGTE applies the GTE predicate on the "issue_number" field.
func IssueNumberGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldIssueNumber, v))
}

// IssueNumberLT applies the LT predicate on the "issue_number" field.
func IssueNumberLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldIssueNumber, v))
}

// IssueNumberLTE applies the LTE predicate on the "issue_number" field.
func IssueNumberLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldIssueNumber, v))
}

// PrNumberEQ applies the EQ predicate on the "pr_number" field.
func PrNumberEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPrNumber, v))
}

// PrNumberNEQ applies the NEQ predicate on the "pr_number" field.
func PrNumberNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPrNumber, v))
}

// PrNumberIn applies the In predicate on the "pr_number" field.
func PrNumberIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPrNumber, vs...))
}

// PrNumberNotIn applies the NotIn predicate on the "pr_number" field.
func PrNumberNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPrNumber, vs...))
}

// PrNumberGT applies the GT predicate on the "pr_number" field.
func PrNumberGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldPrNumber, v))
}

// PrNumberGTE applies the GTE predicate on the "pr_number" field.
func PrNumberGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldPrNumber, v))
}

// PrNumberLT applies the LT predicate on the "pr_number" field.
func PrNumberLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldPrNumber, v))
}

// PrNumberLTE applies the LTE predicate on the "pr_number" field.
func PrNumberLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldPrNumber, v))
}

// PrNumberIsNil applies the IsNil predicate on the "pr_number" field.
func PrNumberIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldPrNumber))
}

// PrNumberNotNil applies the NotNil predicate on the "pr_number" field.
func PrNumberNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldPrNumber))
}

// AgentProfileIDEQ applies the EQ predicate on the "agent_profile_id" field.
func AgentProfileIDEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAgentProfileID, v))
}

// AgentProfileIDNEQ applies the NEQ predicate on the "agent_profile_id" field.
func AgentProfileIDNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAgentProfileID, v))
}

// AgentProfileIDIn applies the In predicate on the "agent_profile_id" field.
func AgentProfileIDIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldAgentProfileID, vs...))
}

// AgentProfileIDNotIn applies the NotIn predicate on the "agent_profile_id" field.
func AgentProfileIDNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldAgentProfileID, vs...))
}

// AgentProfileIDGT applies the GT predicate on the "agent_profile_id" field.
func AgentProfileIDGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldAgentProfileID, v))
}

// AgentProfileIDGTE applies the GTE predicate on the "agent_profile_id" field.
func AgentProfileIDGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldAgentProfileID, v))
}

// AgentProfileIDLT applies the LT predicate on the "agent_profile_id" field.
func AgentProfileIDLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldAgentProfileID, v))
}

// AgentProfileIDLTE applies the LTE predicate on the "agent_profile_id" field.
func AgentProfileIDLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldAgentProfileID, v))
}

// AgentProfileIDIsNil applies the IsNil predicate on the "agent_profile_id" field.
func AgentProfileIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldAgentProfileID))
}

// AgentProfileIDNotNil applies the NotNil predicate on the "agent_profile_id" field.
func AgentProfileIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldAgentProfileID))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldStatus, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldPriority, v))
}

// TriggerSourceEQ applies the EQ predicate on the "trigger_source" field.
func TriggerSourceEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTriggerSource, v))
}

// TriggerSourceNEQ applies the NEQ predicate on the "trigger_source" field.
func TriggerSourceNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTriggerSource, v))
}

// TriggerSourceIn applies the In predicate on the "trigger_source" field.
func TriggerSourceIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTriggerSource, vs...))
}

// TriggerSourceNotIn applies the NotIn predicate on the "trigger_source" field.
func TriggerSourceNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTriggerSource, vs...))
}

// TriggerSourceGT applies the GT predicate on the "trigger_source" field.
func TriggerSourceGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTriggerSource, v))
}

// TriggerSourceGTE applies the GTE predicate on the "trigger_source" field.
func TriggerSourceGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTriggerSource, v))
}

// TriggerSourceLT applies the LT predicate on the "trigger_source" field.
func TriggerSourceLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTriggerSource, v))
}

// TriggerSourceLTE applies the LTE predicate on the "trigger_source" field.
func TriggerSourceLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTriggerSource, v))
}

// TriggerSourceContains applies the Contains predicate on the "trigger_source" field.
func TriggerSourceContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldTriggerSource, v))
}

// TriggerSourceHasPrefix applies the HasPrefix predicate on the "trigger_source" field.
func TriggerSourceHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldTriggerSource, v))
}

// TriggerSourceHasSuffix applies the HasSuffix predicate on the "trigger_source" field.
func TriggerSourceHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldTriggerSource, v))
}

// TriggerSourceEqualFold applies the EqualFold predicate on the "trigger_source" field.
func TriggerSourceEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldTriggerSource, v))
}

// TriggerSourceContainsFold applies the ContainsFold predicate on the "trigger_source" field.
func TriggerSourceContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldTriggerSource, v))
}

// CurrentSessionIDEQ applies the EQ predicate on the "current_session_id" field.
func CurrentSessionIDEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCurrentSessionID, v))
}

// CurrentSessionIDNEQ applies the NEQ predicate on the "current_session_id" field.
func CurrentSessionIDNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCurrentSessionID, v))
}

// CurrentSessionIDIn applies the In predicate on the "current_session_id" field.
func CurrentSessionIDIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCurrentSessionID, vs...))
}

// CurrentSessionIDNotIn applies the NotIn predicate on the "current_session_id" field.
func CurrentSessionIDNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCurrentSessionID, vs...))
}

// CurrentSessionIDGT applies the GT predicate on the "current_session_id" field.
func CurrentSessionIDGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCurrentSessionID, v))
}

// CurrentSessionIDGTE applies the GTE predicate on the "current_session_id" field.
func CurrentSessionIDGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCurrentSessionID, v))
}

// CurrentSessionIDLT applies the LT predicate on the "current_session_id" field.
func CurrentSessionIDLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCurrentSessionID, v))
}

// CurrentSessionIDLTE applies the LTE predicate on the "current_session_id" field.
func CurrentSessionIDLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCurrentSessionID, v))
}

// CurrentSessionIDIsNil applies the IsNil predicate on the "current_session_id" field.
func CurrentSessionIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldCurrentSessionID))
}

// CurrentSessionIDNotNil applies the NotNil predicate on the "current_session_id" field.
func CurrentSessionIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldCurrentSessionID))
}

// TelegramChatIDEQ applies the EQ predicate on the "telegram_chat_id" field.
func TelegramChatIDEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTelegramChatID, v))
}

// TelegramChatIDNEQ applies the NEQ predicate on the "telegram_chat_id" field.
func TelegramChatIDNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTelegramChatID, v))
}

// TelegramChatIDIn applies the In predicate on the "telegram_chat_id" field.
func TelegramChatIDIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTelegramChatID, vs...))
}

// TelegramChatIDNotIn applies the NotIn predicate on the "telegram_chat_id" field.
func TelegramChatIDNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTelegramChatID, vs...))
}

// TelegramChatIDGT applies the GT predicate on the "telegram_chat_id" field.
func TelegramChatIDGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTelegramChatID, v))
}

// TelegramChatIDGTE applies the GTE predicate on the "telegram_chat_id" field.
func TelegramChatIDGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTelegramChatID, v))
}

// TelegramChatIDLT applies the LT predicate on the "telegram_chat_id" field.
func TelegramChatIDLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTelegramChatID, v))
}

// TelegramChatIDLTE applies the LTE predicate on the "telegram_chat_id" field.
func TelegramChatIDLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTelegramChatID, v))
}

// TelegramChatIDContains applies the Contains predicate on the "telegram_chat_id" field.
func TelegramChatIDContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldTelegramChatID, v))
}

// TelegramChatIDHasPrefix applies the HasPrefix predicate on the "telegram_chat_id" field.
func TelegramChatIDHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldTelegramChatID, v))
}

// TelegramChatIDHasSuffix applies the HasSuffix predicate on the "telegram_chat_id" field.
func TelegramChatIDHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldTelegramChatID, v))
}

// TelegramChatIDIsNil applies the IsNil predicate on the "telegram_chat_id" field.
func TelegramChatIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldTelegramChatID))
}

// TelegramChatIDNotNil applies the NotNil predicate on the "telegram_chat_id" field.
func TelegramChatIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldTelegramChatID))
}

// TelegramChatIDEqualFold applies the EqualFold predicate on the "telegram_chat_id" field.
func TelegramChatIDEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldTelegramChatID, v))
}

// TelegramChatIDContainsFold applies the ContainsFold predicate on the "telegram_chat_id" field.
func TelegramChatIDContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldTelegramChatID, v))
}

// TelegramMessageIDEQ applies the EQ predicate on the "telegram_message_id" field.
func TelegramMessageIDEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTelegramMessageID, v))
}

// TelegramMessageIDNEQ applies the NEQ predicate on the "telegram_message_id" field.
func TelegramMessageIDNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTelegramMessageID, v))
}

// TelegramMessageIDIn applies the In predicate on the "telegram_message_id" field.
func TelegramMessageIDIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTelegramMessageID, vs...))
}

// TelegramMessageIDNotIn applies the NotIn predicate on the "telegram_message_id" field.
func TelegramMessageIDNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTelegramMessageID, vs...))
}

// TelegramMessageIDGT applies the GT predicate on the "telegram_message_id" field.
func TelegramMessageIDGT(v int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTelegramMessageID, v))
}

// TelegramMessageIDGTE applies the GTE predicate on the "telegram_message_id" field.
func TelegramMessageIDGTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTelegramMessageID, v))
}

// TelegramMessageIDLT applies the LT predicate on the "telegram_message_id" field.
func TelegramMessageIDLT(v int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTelegramMessageID, v))
}

// TelegramMessageIDLTE applies the LTE predicate on the "telegram_message_id" field.
func TelegramMessageIDLTE(v int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTelegramMessageID, v))
}

// TelegramMessageIDIsNil applies the IsNil predicate on the "telegram_message_id" field.
func TelegramMessageIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldTelegramMessageID))
}

// TelegramMessageIDNotNil applies the NotNil predicate on the "telegram_message_id" field.
func TelegramMessageIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldTelegramMessageID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.Session) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPromptSnapshot applies the HasEdge predicate on the "prompt_snapshot" edge.
func HasPromptSnapshot() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, PromptSnapshotTable, PromptSnapshotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPromptSnapshotWith applies the HasEdge predicate on the "prompt_snapshot" edge with a given conditions (other predicates).
func HasPromptSnapshotWith(preds ...predicate.PromptTemplateSnapshot) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newPromptSnapshotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.Attachment) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommandAudits applies the HasEdge predicate on the "command_audits" edge.
func HasCommandAudits() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommandAuditsTable, CommandAuditsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommandAuditsWith applies the HasEdge predicate on the "command_audits" edge with a given conditions (other predicates).
func HasCommandAuditsWith(preds ...predicate.CommandAudit) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newCommandAuditsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasExecutionLease applies the HasEdge predicate on the "execution_lease" edge.
func HasExecutionLease() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ExecutionLeaseTable, ExecutionLeaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExecutionLeaseWith applies the HasEdge predicate on the "execution_lease" edge with a given conditions (other predicates).
func HasExecutionLeaseWith(preds ...predicate.ExecutionLease) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newExecutionLeaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Task) predicate.Task {
	return predicate.Task(sql.NotPredicates(p))
}
