// Code generated by ent, DO NOT EDIT.

package agentprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the agentprofile type in the database.
	Label = "agent_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldSupportsImage holds the string denoting the supports_image field in the database.
	FieldSupportsImage = "supports_image"
	// FieldSupportsResume holds the string denoting the supports_resume field in the database.
	FieldSupportsResume = "supports_resume"
	// FieldConfigJSON holds the string denoting the config_json field in the database.
	FieldConfigJSON = "config_json"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the agentprofile in the database.
	Table = "agent_profiles"
)

// Columns holds all SQL columns for agentprofile fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldModel,
	FieldSupportsImage,
	FieldSupportsResume,
	FieldConfigJSON,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultSupportsImage holds the default value on creation for the "supports_image" field.
	DefaultSupportsImage bool
	// DefaultSupportsResume holds the default value on creation for the "supports_resume" field.
	DefaultSupportsResume bool
	// DefaultConfigJSON holds the default value on creation for the "config_json" field.
	DefaultConfigJSON string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AgentProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// BySupportsImage orders the results by the supports_image field.
func BySupportsImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsImage, opts...).ToFunc()
}

// BySupportsResume orders the results by the supports_resume field.
func BySupportsResume(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportsResume, opts...).ToFunc()
}

// ByConfigJSON orders the results by the config_json field.
func ByConfigJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigJSON, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
