// Code generated by ent, DO NOT EDIT.

package agentprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldProvider, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldModel, v))
}

// SupportsImage applies equality check predicate on the "supports_image" field. It's identical to SupportsImageEQ.
func SupportsImage(v bool) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldSupportsImage, v))
}

// SupportsResume applies equality check predicate on the "supports_resume" field. It's identical to SupportsResumeEQ.
func SupportsResume(v bool) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldSupportsResume, v))
}

// ConfigJSON applies equality check predicate on the "config_json" field. It's identical to ConfigJSONEQ.
func ConfigJSON(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldConfigJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldContainsFold(FieldProvider, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldContainsFold(FieldModel, v))
}

// SupportsImageEQ applies the EQ predicate on the "supports_image" field.
func SupportsImageEQ(v bool) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldSupportsImage, v))
}

// SupportsImageNEQ applies the NEQ predicate on the "supports_image" field.
func SupportsImageNEQ(v bool) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNEQ(FieldSupportsImage, v))
}

// SupportsResumeEQ applies the EQ predicate on the "supports_resume" field.
func SupportsResumeEQ(v bool) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldSupportsResume, v))
}

// SupportsResumeNEQ applies the NEQ predicate on the "supports_resume" field.
func SupportsResumeNEQ(v bool) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNEQ(FieldSupportsResume, v))
}

// ConfigJSONEQ applies the EQ predicate on the "config_json" field.
func ConfigJSONEQ(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldConfigJSON, v))
}

// ConfigJSONNEQ applies the NEQ predicate on the "config_json" field.
func ConfigJSONNEQ(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNEQ(FieldConfigJSON, v))
}

// ConfigJSONIn applies the In predicate on the "config_json" field.
func ConfigJSONIn(vs ...string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldIn(FieldConfigJSON, vs...))
}

// ConfigJSONNotIn applies the NotIn predicate on the "config_json" field.
func ConfigJSONNotIn(vs ...string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNotIn(FieldConfigJSON, vs...))
}

// ConfigJSONGT applies the GT predicate on the "config_json" field.
func ConfigJSONGT(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGT(FieldConfigJSON, v))
}

// ConfigJSONGTE applies the GTE predicate on the "config_json" field.
func ConfigJSONGTE(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGTE(FieldConfigJSON, v))
}

// ConfigJSONLT applies the LT predicate on the "config_json" field.
func ConfigJSONLT(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLT(FieldConfigJSON, v))
}

// ConfigJSONLTE applies the LTE predicate on the "config_json" field.
func ConfigJSONLTE(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLTE(FieldConfigJSON, v))
}

// ConfigJSONContains applies the Contains predicate on the "config_json" field.
func ConfigJSONContains(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldContains(FieldConfigJSON, v))
}

// ConfigJSONHasPrefix applies the HasPrefix predicate on the "config_json" field.
func ConfigJSONHasPrefix(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldHasPrefix(FieldConfigJSON, v))
}

// ConfigJSONHasSuffix applies the HasSuffix predicate on the "config_json" field.
func ConfigJSONHasSuffix(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldHasSuffix(FieldConfigJSON, v))
}

// ConfigJSONEqualFold applies the EqualFold predicate on the "config_json" field.
func ConfigJSONEqualFold(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEqualFold(FieldConfigJSON, v))
}

// ConfigJSONContainsFold applies the ContainsFold predicate on the "config_json" field.
func ConfigJSONContainsFold(v string) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldContainsFold(FieldConfigJSON, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AgentProfile {
	return predicate.AgentProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentProfile) predicate.AgentProfile {
	return predicate.AgentProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentProfile) predicate.AgentProfile {
	return predicate.AgentProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentProfile) predicate.AgentProfile {
	return predicate.AgentProfile(sql.NotPredicates(p))
}
