// Code generated by ent, DO NOT EDIT.

package prompttemplatesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the prompttemplatesnapshot type in the database.
	Label = "prompt_template_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSystemPrompt holds the string denoting the system_prompt field in the database.
	FieldSystemPrompt = "system_prompt"
	// FieldTaskPrompt holds the string denoting the task_prompt field in the database.
	FieldTaskPrompt = "task_prompt"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldModelVersion holds the string denoting the model_version field in the database.
	FieldModelVersion = "model_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// Table holds the table name of the prompttemplatesnapshot in the database.
	Table = "prompt_template_snapshots"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "prompt_template_snapshots"
	// TaskInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TaskInverseTable = "tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "task_prompt_snapshot"
)

// Columns holds all SQL columns for prompttemplatesnapshot fields.
var Columns = []string{
	FieldID,
	FieldSystemPrompt,
	FieldTaskPrompt,
	FieldModelName,
	FieldModelVersion,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "prompt_template_snapshots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"task_prompt_snapshot",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultModelVersion holds the default value on creation for the "model_version" field.
	DefaultModelVersion string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the PromptTemplateSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySystemPrompt orders the results by the system_prompt field.
func BySystemPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemPrompt, opts...).ToFunc()
}

// ByTaskPrompt orders the results by the task_prompt field.
func ByTaskPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskPrompt, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByModelVersion orders the results by the model_version field.
func ByModelVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTaskField orders the results by task field.
func ByTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStep(), sql.OrderByField(field, opts...))
	}
}
func newTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TaskTable, TaskColumn),
	)
}
