// Code generated by ent, DO NOT EDIT.

package prompttemplatesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloverstd/ccmate/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLTE(FieldID, id))
}

// SystemPrompt applies equality check predicate on the "system_prompt" field. It's identical to SystemPromptEQ.
func SystemPrompt(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldSystemPrompt, v))
}

// TaskPrompt applies equality check predicate on the "task_prompt" field. It's identical to TaskPromptEQ.
func TaskPrompt(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldTaskPrompt, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldModelName, v))
}

// ModelVersion applies equality check predicate on the "model_version" field. It's identical to ModelVersionEQ.
func ModelVersion(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldModelVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// SystemPromptEQ applies the EQ predicate on the "system_prompt" field.
func SystemPromptEQ(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldSystemPrompt, v))
}

// SystemPromptNEQ applies the NEQ predicate on the "system_prompt" field.
func SystemPromptNEQ(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNEQ(FieldSystemPrompt, v))
}

// SystemPromptIn applies the In predicate on the "system_prompt" field.
func SystemPromptIn(vs ...string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldIn(FieldSystemPrompt, vs...))
}

// SystemPromptNotIn applies the NotIn predicate on the "system_prompt" field.
func SystemPromptNotIn(vs ...string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNotIn(FieldSystemPrompt, vs...))
}

// SystemPromptGT applies the GT predicate on the "system_prompt" field.
func SystemPromptGT(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGT(FieldSystemPrompt, v))
}

// SystemPromptGTE applies the GTE predicate on the "system_prompt" field.
func SystemPromptGTE(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGTE(FieldSystemPrompt, v))
}

// SystemPromptLT applies the LT predicate on the "system_prompt" field.
func SystemPromptLT(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLT(FieldSystemPrompt, v))
}

// SystemPromptLTE applies the LTE predicate on the "system_prompt" field.
func SystemPromptLTE(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLTE(FieldSystemPrompt, v))
}

// SystemPromptContains applies the Contains predicate on the "system_prompt" field.
func SystemPromptContains(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldContains(FieldSystemPrompt, v))
}

// SystemPromptHasPrefix applies the HasPrefix predicate on the "system_prompt" field.
func SystemPromptHasPrefix(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldHasPrefix(FieldSystemPrompt, v))
}

// SystemPromptHasSuffix applies the HasSuffix predicate on the "system_prompt" field.
func SystemPromptHasSuffix(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldHasSuffix(FieldSystemPrompt, v))
}

// SystemPromptEqualFold applies the EqualFold predicate on the "system_prompt" field.
func SystemPromptEqualFold(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEqualFold(FieldSystemPrompt, v))
}

// SystemPromptContainsFold applies the ContainsFold predicate on the "system_prompt" field.
func SystemPromptContainsFold(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldContainsFold(FieldSystemPrompt, v))
}

// TaskPromptEQ applies the EQ predicate on the "task_prompt" field.
func TaskPromptEQ(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldTaskPrompt, v))
}

// TaskPromptNEQ applies the NEQ predicate on the "task_prompt" field.
func TaskPromptNEQ(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNEQ(FieldTaskPrompt, v))
}

// TaskPromptIn applies the In predicate on the "task_prompt" field.
func TaskPromptIn(vs ...string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldIn(FieldTaskPrompt, vs...))
}

// TaskPromptNotIn applies the NotIn predicate on the "task_prompt" field.
func TaskPromptNotIn(vs ...string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNotIn(FieldTaskPrompt, vs...))
}

// TaskPromptGT applies the GT predicate on the "task_prompt" field.
func TaskPromptGT(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGT(FieldTaskPrompt, v))
}

// TaskPromptGTE applies the GTE predicate on the "task_prompt" field.
func TaskPromptGTE(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGTE(FieldTaskPrompt, v))
}

// TaskPromptLT applies the LT predicate on the "task_prompt" field.
func TaskPromptLT(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLT(FieldTaskPrompt, v))
}

// TaskPromptLTE applies the LTE predicate on the "task_prompt" field.
func TaskPromptLTE(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLTE(FieldTaskPrompt, v))
}

// TaskPromptContains applies the Contains predicate on the "task_prompt" field.
func TaskPromptContains(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldContains(FieldTaskPrompt, v))
}

// TaskPromptHasPrefix applies the HasPrefix predicate on the "task_prompt" field.
func TaskPromptHasPrefix(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldHasPrefix(FieldTaskPrompt, v))
}

// TaskPromptHasSuffix applies the HasSuffix predicate on the "task_prompt" field.
func TaskPromptHasSuffix(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldHasSuffix(FieldTaskPrompt, v))
}

// TaskPromptEqualFold applies the EqualFold predicate on the "task_prompt" field.
func TaskPromptEqualFold(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEqualFold(FieldTaskPrompt, v))
}

// TaskPromptContainsFold applies the ContainsFold predicate on the "task_prompt" field.
func TaskPromptContainsFold(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldContainsFold(FieldTaskPrompt, v))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldContainsFold(FieldModelName, v))
}

// ModelVersionEQ applies the EQ predicate on the "model_version" field.
func ModelVersionEQ(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldModelVersion, v))
}

// ModelVersionNEQ applies the NEQ predicate on the "model_version" field.
func ModelVersionNEQ(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNEQ(FieldModelVersion, v))
}

// ModelVersionIn applies the In predicate on the "model_version" field.
func ModelVersionIn(vs ...string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldIn(FieldModelVersion, vs...))
}

// ModelVersionNotIn applies the NotIn predicate on the "model_version" field.
func ModelVersionNotIn(vs ...string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNotIn(FieldModelVersion, vs...))
}

// ModelVersionGT applies the GT predicate on the "model_version" field.
func ModelVersionGT(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGT(FieldModelVersion, v))
}

// ModelVersionGTE applies the GTE predicate on the "model_version" field.
func ModelVersionGTE(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGTE(FieldModelVersion, v))
}

// ModelVersionLT applies the LT predicate on the "model_version" field.
func ModelVersionLT(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLT(FieldModelVersion, v))
}

// ModelVersionLTE applies the LTE predicate on the "model_version" field.
func ModelVersionLTE(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLTE(FieldModelVersion, v))
}

// ModelVersionContains applies the Contains predicate on the "model_version" field.
func ModelVersionContains(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldContains(FieldModelVersion, v))
}

// ModelVersionHasPrefix applies the HasPrefix predicate on the "model_version" field.
func ModelVersionHasPrefix(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldHasPrefix(FieldModelVersion, v))
}

// ModelVersionHasSuffix applies the HasSuffix predicate on the "model_version" field.
func ModelVersionHasSuffix(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldHasSuffix(FieldModelVersion, v))
}

// ModelVersionEqualFold applies the EqualFold predicate on the "model_version" field.
func ModelVersionEqualFold(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEqualFold(FieldModelVersion, v))
}

// ModelVersionContainsFold applies the ContainsFold predicate on the "model_version" field.
func ModelVersionContainsFold(v string) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldContainsFold(FieldModelVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromptTemplateSnapshot) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromptTemplateSnapshot) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromptTemplateSnapshot) predicate.PromptTemplateSnapshot {
	return predicate.PromptTemplateSnapshot(sql.NotPredicates(p))
}
